ALTER USER S4QPLANO DISABLE PASSWORD LIFETIME

//S4QPLANO é o usuário

ALTER USER DATASPRINT DISABLE PASSWORD LIFETIME

ALTER USER DATASPRINT ACTIVATE USER NOW

select SAPS4P.TVARVC, "LAST_MODIFY_TIME" FROM SYS.M_TABLE_STATISTICS order by "LAST_MODIFY_TIME" desc

-- Shrink Datavolume Hana
ALTER SYSTEM RECLAIM DATAVOLUME 106 DEFRAGMENT;

-- Consultas Tamanho DB
SELECT A.DATABASE_NAME, A.HOST, A.SERVICE_NAME, B.DATA AS DATA_GB, C.LOG AS LOG_GB 
FROM "SYS"."M_VOLUMES_" AS A 
INNER JOIN (SELECT VOLUME_ID, DATABASE_NAME, ROUND(DATA_SIZE/1024/1024/1024, 3) AS DATA FROM "SYS"."M_VOLUME_SIZES_" 
WHERE LOG_SIZE =-1) AS B ON A.VOLUME_ID = B.VOLUME_ID AND A.DATABASE_NAME = B.DATABASE_NAME INNER JOIN

(SELECT VOLUME_ID, DATABASE_NAME, ROUND(LOG_SIZE/1024/1024/1024, 3) AS LOG FROM "SYS"."M_VOLUME_SIZES_" 
WHERE DATA_SIZE =-1) AS C ON B.VOLUME_ID = C.VOLUME_ID AND B.DATABASE_NAME = C.DATABASE_NAME

SELECT A.DATABASE_NAME, SUM(B.DATA) AS DATA_GB FROM "SYS"."M_VOLUMES_" AS A 
INNER JOIN (SELECT VOLUME_ID, DATABASE_NAME, 
ROUND(DATA_SIZE/1024/1024/1024, 3) AS DATA FROM "SYS"."M_VOLUME_SIZES_" 
WHERE LOG_SIZE =-1) AS B ON A.VOLUME_ID = B.VOLUME_ID 
AND A.DATABASE_NAME = B.DATABASE_NAME GROUP BY A.DATABASE_NAME;