SELECT 
A.DOCNUM AS "Número documento", 
A.NFTYPE AS "Tipo de NFe", 
A.DIRECT AS "Direção", 
A.CREDAT AS "Data da Criação", 
A.NFENUM AS "Número da Nota",
B.INT_EVENT AS "Evento",
B.TEXT AS "Texto"
FROM SAPS4P.J_1BNFDOC AS A
INNER JOIN SAPS4P.J_1BNFE_CCE AS B 
ON A.DOCNUM = B.DOCNUM
AND A.MANDT = B.MANDT
WHERE A.MANDT = '400' AND A.DIRECT = '2' 
AND A.CREDAT BETWEEN '20200301' AND '20200330'