-- AUTOR: DANIEL FARIAS
-- SOLICITANTE: ERALDO
-- DESCRIÇÃO: select lower ('CORREÇÃO DAS MATRICULAS QUE POSSUIAM SÓ USUÁRIO OU PROPRIETÁRIO')
-- DATA INICIO 18/04/2018
-- DATA FIM 18/04/2018
-- OBSERVAÇÃO:
 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
select 'insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('||CHR(39)||'cadastro.sequence_cliente_imovel'||CHR(39)||')), ' ||clie_id||', '|| imov_id ||', '||CHR(39)|| clim_dtrelacaoinicio ||CHR(39)||', null, null, now(), '|| 
CASE
           when crtp_id = 1 THEN 2
           ELSE 1
      end ||','||
CASE
           WHEN clim_icnomeconta = 1 THEN 2
           ELSE 1
      end ||' );'as aa
from cadastro.cliente_imovel
where imov_id in (
					select ci.imov_id from cadastro.cliente_imovel as ci
					inner join cadastro.imovel as i
					on ci.imov_id = i.imov_id
					where i.last_id in (3,5,6,8)
					       AND i.lest_id in (3,5,6,8)
					group by ci.imov_id
					having count (ci.imov_id) < 2
				 )


insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90484, 90484, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90468, 90468, '2013-12-14', null, null, now(), 2,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90441, 90441, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90522, 90522, '2013-12-14', null, null, now(), 2,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90514, 90514, '2013-12-14', null, null, now(), 2,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90530, 90530, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908099, 907895, '2014-01-10', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908321, 907984, '2014-01-21', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908603, 908100, '2014-02-05', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908467, 908034, '2014-01-28', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908137, 907904, '2014-01-13', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908649, 908120, '2014-02-07', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908081, 907886, '2014-01-09', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908533, 908070, '2014-01-31', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908481, 908044, '2014-01-29', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908435, 908023, '2014-01-27', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908507, 908059, '2014-01-29', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 601438, 601438, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89885, 89885, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 87467, 87467, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 87416, 87416, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90174, 90174, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 88951, 88951, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 87459, 87459, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90239, 90239, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 88625, 88625, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90140, 90140, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 88480, 88480, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89370, 89370, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89923, 89923, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89532, 89532, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90042, 90042, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89966, 89966, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89958, 89958, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90077, 90077, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 89982, 89982, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90336, 90336, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 87971, 87971, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 87955, 87955, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908691, 908140, '2014-02-11', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908713, 908147, '2014-02-12', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908737, 908158, '2014-02-12', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908739, 908159, '2014-02-12', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908747, 908161, '2014-02-12', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908749, 908162, '2014-02-13', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908659, 908184, '2014-02-17', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908839, 908188, '2014-02-17', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908929, 908207, '2014-02-19', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 908997, 908228, '2014-02-21', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909049, 908248, '2014-02-25', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909137, 908281, '2014-02-28', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909269, 908323, '2014-03-11', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909357, 908358, '2014-03-14', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909427, 908374, '2014-03-18', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909429, 908375, '2014-03-18', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909429, 908376, '2014-03-18', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909453, 908390, '2014-03-19', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909517, 908417, '2014-03-21', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 909543, 908423, '2014-03-24', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 86525, 86525, '2014-04-22', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 86550, 86550, '2014-04-22', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 910573, 908877, '2014-05-16', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 910577, 908878, '2014-05-16', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 910591, 908893, '2014-05-19', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 40061, 908900, '2014-05-19', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 671860, 90050, '2013-12-14', null, null, now(), 1,1 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 655074, 87157, '2014-11-21', null, null, now(), 1,2 );
insert into cadastro.cliente_imovel (clim_id, clie_id, imov_id, clim_dtrelacaoinicio, clim_dtrelacaofim, cifr_id, clim_tmultimaalteracao, crtp_id, clim_icnomeconta) values ((SELECT NEXTVAL ('cadastro.sequence_cliente_imovel')), 90182, 90182, '2013-12-14', null, null, now(), 1,1 );