USE MayorQuimica_Importacao_Intermediaria
GO


/* update particulares do banco da mayor quimica */
update tbl_usuarios set codempresa = 2
delete from tbl_empresas where codempresa = 1
GO
/*************************************************/



ALTER TABLE TBL_CLIENTES
	ADD COD_IMPORTACAO_TEMP INT NULL
GO



CREATE TABLE [CLIENTES2] (
	[NOME       ] [char] (60) COLLATE Latin1_General_CI_AI NULL ,
	[FANTASIA   ] [char] (40) COLLATE Latin1_General_CI_AI NULL ,
	[CONTATO    ] [char] (35) COLLATE Latin1_General_CI_AI NULL ,
	[IE         ] [char] (16) COLLATE Latin1_General_CI_AI NULL ,
	[IM         ] [char] (16) COLLATE Latin1_General_CI_AI NULL ,
	[CGC        ] [char] (19) COLLATE Latin1_General_CI_AI NULL ,
	[TIPO       ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[ENDERE     ] [char] (40) COLLATE Latin1_General_CI_AI NULL ,
	[NUMERO     ] [char] (5) COLLATE Latin1_General_CI_AI NULL ,
	[CMPL       ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[COMPLE     ] [char] (35) COLLATE Latin1_General_CI_AI NULL ,
	[CIDADE     ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[ESTADO     ] [char] (2) COLLATE Latin1_General_CI_AI NULL ,
	[CEP        ] [char] (9) COLLATE Latin1_General_CI_AI NULL ,
	[FONE       ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[FAX        ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[EMAIL      ] [char] (80) COLLATE Latin1_General_CI_AI NULL ,
	[ADICIONAL1 ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[ADICIONAL2 ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[OBS        ] [char] (254) COLLATE Latin1_General_CI_AI NULL ,
	[CELULAR    ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[CREDITO    ] [numeric](20, 4) NULL ,
	[PAI        ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[MAE        ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[CONJUGE    ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[NATURAL    ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[PROFISSAO  ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[CONVENIO   ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[DATANAS    ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[CADASTRO   ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[ULTIMACO   ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[PROXDATA   ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[TIPO_COB   ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[ENDERE_COB ] [char] (40) COLLATE Latin1_General_CI_AI NULL ,
	[NUMERO_COB ] [char] (5) COLLATE Latin1_General_CI_AI NULL ,
	[CMPL_COB   ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[COMPLE_COB ] [char] (35) COLLATE Latin1_General_CI_AI NULL ,
	[CIDADE_COB ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[ESTADO_COB ] [char] (2) COLLATE Latin1_General_CI_AI NULL ,
	[CEP_COB    ] [char] (9) COLLATE Latin1_General_CI_AI NULL ,
	[CUSTO      ] [numeric](20, 4) NULL ,
	[COMPRA     ] [numeric](20, 4) NULL ,
	[ATIVO      ] [bit] NULL ,
	[MOSTRAR    ] [char] (1) COLLATE Latin1_General_CI_AI NULL,
	COD_IMPORTACAO_TEMP INT NULL
) ON [PRIMARY]
GO




INSERT INTO CLIENTES2( [NOME], [FANTASIA], [CONTATO], [IE], [IM], [CGC], [TIPO], [ENDERE], [NUMERO], [CMPL], [COMPLE], [CIDADE], [ESTADO], [CEP], [FONE], [FAX], [EMAIL], [ADICIONAL1], [ADICIONAL2], [OBS], [CELULAR], [CREDITO], [PAI], [MAE], [CONJUGE], [NATURAL], [PROFISSAO], [CONVENIO], [DATANAS], [CADASTRO], [ULTIMACO], [PROXDATA], [TIPO_COB], [ENDERE_COB], [NUMERO_COB], [CMPL_COB], [COMPLE_COB], [CIDADE_COB], [ESTADO_COB], [CEP_COB], [CUSTO], [COMPRA], [ATIVO], [MOSTRAR] )
	SELECT [NOME], [FANTASIA], [CONTATO], [IE], [IM], [CGC], [TIPO], [ENDERE], [NUMERO], [CMPL], [COMPLE], [CIDADE], [ESTADO], [CEP], [FONE], [FAX], [EMAIL], [ADICIONAL1], [ADICIONAL2], [OBS], [CELULAR], [CREDITO], [PAI], [MAE], [CONJUGE], [NATURAL], [PROFISSAO], [CONVENIO], [DATANAS], [CADASTRO], [ULTIMACO], [PROXDATA], [TIPO_COB], [ENDERE_COB], [NUMERO_COB], [CMPL_COB], [COMPLE_COB], [CIDADE_COB], [ESTADO_COB], [CEP_COB], [CUSTO], [COMPRA], [ATIVO], [MOSTRAR] FROM CLIENTES
GO



	




DROP TABLE CLIENTES
GO

CREATE TABLE [CLIENTES] (
	COD INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[NOME       ] [char] (60) COLLATE Latin1_General_CI_AI NULL ,
	[FANTASIA   ] [char] (40) COLLATE Latin1_General_CI_AI NULL ,
	[CONTATO    ] [char] (35) COLLATE Latin1_General_CI_AI NULL ,
	[IE         ] [char] (16) COLLATE Latin1_General_CI_AI NULL ,
	[IM         ] [char] (16) COLLATE Latin1_General_CI_AI NULL ,
	[CGC        ] [char] (19) COLLATE Latin1_General_CI_AI NULL ,
	[TIPO       ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[ENDERE     ] [char] (40) COLLATE Latin1_General_CI_AI NULL ,
	[NUMERO     ] [char] (5) COLLATE Latin1_General_CI_AI NULL ,
	[CMPL       ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[COMPLE     ] [char] (35) COLLATE Latin1_General_CI_AI NULL ,
	[CIDADE     ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[ESTADO     ] [char] (2) COLLATE Latin1_General_CI_AI NULL ,
	[CEP        ] [char] (9) COLLATE Latin1_General_CI_AI NULL ,
	[FONE       ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[FAX        ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[EMAIL      ] [char] (80) COLLATE Latin1_General_CI_AI NULL ,
	[ADICIONAL1 ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[ADICIONAL2 ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[OBS        ] [char] (254) COLLATE Latin1_General_CI_AI NULL ,
	[CELULAR    ] [char] (20) COLLATE Latin1_General_CI_AI NULL ,
	[CREDITO    ] [numeric](20, 4) NULL ,
	[PAI        ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[MAE        ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[CONJUGE    ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[NATURAL    ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[PROFISSAO  ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[CONVENIO   ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[DATANAS    ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[CADASTRO   ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[ULTIMACO   ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[PROXDATA   ] [nvarchar] (100) COLLATE Latin1_General_CI_AI NULL ,
	[TIPO_COB   ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[ENDERE_COB ] [char] (40) COLLATE Latin1_General_CI_AI NULL ,
	[NUMERO_COB ] [char] (5) COLLATE Latin1_General_CI_AI NULL ,
	[CMPL_COB   ] [char] (15) COLLATE Latin1_General_CI_AI NULL ,
	[COMPLE_COB ] [char] (35) COLLATE Latin1_General_CI_AI NULL ,
	[CIDADE_COB ] [char] (30) COLLATE Latin1_General_CI_AI NULL ,
	[ESTADO_COB ] [char] (2) COLLATE Latin1_General_CI_AI NULL ,
	[CEP_COB    ] [char] (9) COLLATE Latin1_General_CI_AI NULL ,
	[CUSTO      ] [numeric](20, 4) NULL ,
	[COMPRA     ] [numeric](20, 4) NULL ,
	[ATIVO      ] [bit] NULL ,
	[MOSTRAR    ] [char] (1) COLLATE Latin1_General_CI_AI NULL,
	COD_IMPORTACAO_TEMP INT NULL
) ON [PRIMARY]
GO

INSERT INTO CLIENTES( [NOME], [FANTASIA], [CONTATO], [IE], [IM], [CGC], [TIPO], [ENDERE], [NUMERO], [CMPL], [COMPLE], [CIDADE], [ESTADO], [CEP], [FONE], [FAX], [EMAIL], [ADICIONAL1], [ADICIONAL2], [OBS], [CELULAR], [CREDITO], [PAI], [MAE], [CONJUGE], [NATURAL], [PROFISSAO], [CONVENIO], [DATANAS], [CADASTRO], [ULTIMACO], [PROXDATA], [TIPO_COB], [ENDERE_COB], [NUMERO_COB], [CMPL_COB], [COMPLE_COB], [CIDADE_COB], [ESTADO_COB], [CEP_COB], [CUSTO], [COMPRA], [ATIVO], [MOSTRAR] )
	SELECT  [NOME], [FANTASIA], [CONTATO], [IE], [IM], [CGC], [TIPO], [ENDERE], [NUMERO], [CMPL], [COMPLE], [CIDADE], [ESTADO], [CEP], [FONE], [FAX], [EMAIL], [ADICIONAL1], [ADICIONAL2], [OBS], [CELULAR], [CREDITO], [PAI], [MAE], [CONJUGE], [NATURAL], [PROFISSAO], [CONVENIO], [DATANAS], [CADASTRO], [ULTIMACO], [PROXDATA], [TIPO_COB], [ENDERE_COB], [NUMERO_COB], [CMPL_COB], [COMPLE_COB], [CIDADE_COB], [ESTADO_COB], [CEP_COB], [CUSTO], [COMPRA], [ATIVO], [MOSTRAR]  FROM CLIENTES2
GO

DROP TABLE CLIENTES2
GO



ALTER TABLE CLIENTES
	ALTER COLUMN ENDERE NVARCHAR(100)
GO
ALTER TABLE CLIENTES
	ALTER COLUMN ENDERE_COB NVARCHAR(100)
GO
ALTER TABLE CLIENTES
	ALTER COLUMN TIPO NVARCHAR(100)
GO
ALTER TABLE CLIENTES
	ALTER COLUMN TIPO_COB NVARCHAR(100)
GO



ALTER TABLE CLIENTES
	ADD CNPJ NVARCHAR(14) NULL
GO
ALTER TABLE CLIENTES
	ADD CPF NVARCHAR(11) NULL
GO


UPDATE 	CLIENTES
SET 	CIDADE = RTRIM(LTRIM(UPPER(CIDADE))), COMPLE = RTRIM(LTRIM(UPPER(COMPLE))), ESTADO = RTRIM(LTRIM(UPPER(ESTADO))),
		FONE = RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FONE, ' ', ''), '(', ''), ')', ''), '-', ''), '.', ''))),
		FAX = RTRIM(LTRIM(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FAX, ' ', ''), '(', ''), ')', ''), '-', ''), '.', '')))
GO
UPDATE 	CLIENTES 
SET 	CIDADE = REPLACE(CIDADE, '·', 'U')
GO
UPDATE 	CLIENTES 
SET 	CIDADE = REPLACE(CIDADE, 'JOÒO', 'JOAO')
GO
UPDATE 	CLIENTES 
SET 	CIDADE = REPLACE(CIDADE, 'Ý', 'I')
GO

UPDATE 	CLIENTES 
SET 	NOME = RTRIM(LTRIM(UPPER(NOME))), FANTASIA = RTRIM(LTRIM(UPPER(FANTASIA))), CONTATO = RTRIM(LTRIM(UPPER(CONTATO))),
		ENDERE = RTRIM(LTRIM(UPPER(ENDERE))), TIPO = RTRIM(LTRIM(UPPER(TIPO))), NUMERO = RTRIM(LTRIM(UPPER(NUMERO))),
		CMPL = RTRIM(LTRIM(UPPER(CMPL))), ESTADO = RTRIM(LTRIM(UPPER(ESTADO))), EMAIL = RTRIM(LTRIM(UPPER(EMAIL))),
		OBS = RTRIM(LTRIM(UPPER(OBS))), TIPO_COB = RTRIM(LTRIM(UPPER(TIPO_COB))), ENDERE_COB = RTRIM(LTRIM(UPPER(ENDERE_COB))),
		NUMERO_COB = RTRIM(LTRIM(UPPER(NUMERO_COB))), CMPL_COB = RTRIM(LTRIM(UPPER(CMPL_COB))), COMPLE_COB = RTRIM(LTRIM(UPPER(COMPLE_COB))),
		CIDADE_COB = RTRIM(LTRIM(UPPER(CIDADE_COB))), ESTADO_COB = RTRIM(LTRIM(UPPER(ESTADO_COB)))
GO

UPDATE 	CLIENTES 
SET 	IE = REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(IE))), '.', ''), '-', ''), '/', ''),
		CGC = REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(CGC))), '.', ''), '-', ''), '/', ''),
		CEP = REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(CEP))), '.', ''), '-', ''), '/', ''),
		CEP_COB = REPLACE(REPLACE(REPLACE(RTRIM(LTRIM(UPPER(CEP_COB))), '.', ''), '-', ''), '/', '')
GO



UPDATE	CLIENTES SET CIDADE_COB = NULL WHERE RTRIM(LTRIM(CIDADE_COB)) = ''
GO
UPDATE	CLIENTES SET ESTADO_COB = NULL WHERE RTRIM(LTRIM(ESTADO_COB)) = ''
GO
UPDATE	CLIENTES SET CIDADE = NULL WHERE RTRIM(LTRIM(CIDADE)) = ''
GO
UPDATE	CLIENTES SET ESTADO = NULL WHERE RTRIM(LTRIM(ESTADO)) = ''
GO
UPDATE	CLIENTES SET CIDADE_COB = NULL WHERE CIDADE_COB = 'NULL'
GO
UPDATE	CLIENTES SET ESTADO_COB = NULL WHERE ESTADO_COB = 'NULL'
GO
UPDATE	CLIENTES SET CIDADE = NULL WHERE CIDADE = 'NULL'
GO
UPDATE	CLIENTES SET ESTADO = NULL WHERE ESTADO = 'NULL'
GO

UPDATE	CLIENTES SET FANTASIA = NULL WHERE RTRIM(LTRIM(FANTASIA)) = ''
GO

UPDATE	CLIENTES SET CEP_COB = NULL WHERE RTRIM(LTRIM(CEP_COB)) = ''
UPDATE	CLIENTES SET COMPLE_COB = NULL WHERE RTRIM(LTRIM(COMPLE_COB)) = ''
UPDATE	CLIENTES SET CMPL_COB = NULL WHERE RTRIM(LTRIM(CMPL_COB)) = ''
UPDATE	CLIENTES SET NUMERO_COB = NULL WHERE RTRIM(LTRIM(NUMERO_COB)) = ''
UPDATE	CLIENTES SET ENDERE_COB = NULL WHERE RTRIM(LTRIM(ENDERE_COB)) = ''
UPDATE	CLIENTES SET TIPO_COB = NULL WHERE RTRIM(LTRIM(TIPO_COB)) = ''
UPDATE	CLIENTES SET ULTIMACO = NULL WHERE RTRIM(LTRIM(ULTIMACO)) = ''
UPDATE	CLIENTES SET CADASTRO = NULL WHERE RTRIM(LTRIM(CADASTRO)) = ''
UPDATE	CLIENTES SET DATANAS = NULL WHERE RTRIM(LTRIM(DATANAS)) = ''
UPDATE	CLIENTES SET CONVENIO = NULL WHERE RTRIM(LTRIM(CONVENIO)) = ''
UPDATE	CLIENTES SET PROFISSAO = NULL WHERE RTRIM(LTRIM(PROFISSAO)) = ''
UPDATE	CLIENTES SET NATURAL = NULL WHERE RTRIM(LTRIM(NATURAL)) = ''
UPDATE	CLIENTES SET CONJUGE = NULL WHERE RTRIM(LTRIM(CONJUGE)) = ''
UPDATE	CLIENTES SET MAE = NULL WHERE RTRIM(LTRIM(MAE)) = ''
UPDATE	CLIENTES SET PAI = NULL WHERE RTRIM(LTRIM(PAI)) = ''
UPDATE	CLIENTES SET CELULAR = NULL WHERE RTRIM(LTRIM(CELULAR)) = ''
UPDATE	CLIENTES SET OBS = NULL WHERE RTRIM(LTRIM(OBS)) = ''
UPDATE	CLIENTES SET ADICIONAL1 = NULL WHERE RTRIM(LTRIM(ADICIONAL1)) = ''
UPDATE	CLIENTES SET ADICIONAL2 = NULL WHERE RTRIM(LTRIM(ADICIONAL2)) = ''
UPDATE	CLIENTES SET EMAIL = NULL WHERE RTRIM(LTRIM(EMAIL)) = ''
UPDATE	CLIENTES SET FAX = NULL WHERE RTRIM(LTRIM(FAX)) = ''
UPDATE	CLIENTES SET FONE = NULL WHERE RTRIM(LTRIM(FONE)) = ''
UPDATE	CLIENTES SET CEP = NULL WHERE RTRIM(LTRIM(CEP)) = ''
UPDATE	CLIENTES SET ESTADO = NULL WHERE RTRIM(LTRIM(ESTADO)) = ''
UPDATE	CLIENTES SET CIDADE = NULL WHERE RTRIM(LTRIM(CIDADE)) = ''
UPDATE	CLIENTES SET COMPLE = NULL WHERE RTRIM(LTRIM(COMPLE)) = ''
UPDATE	CLIENTES SET CMPL = NULL WHERE RTRIM(LTRIM(CMPL)) = ''
UPDATE	CLIENTES SET NUMERO = NULL WHERE RTRIM(LTRIM(NUMERO)) = ''
UPDATE	CLIENTES SET ENDERE = NULL WHERE RTRIM(LTRIM(ENDERE)) = ''
UPDATE	CLIENTES SET TIPO = NULL WHERE RTRIM(LTRIM(TIPO)) = ''
UPDATE	CLIENTES SET CGC = NULL WHERE RTRIM(LTRIM(CGC)) = ''
UPDATE	CLIENTES SET IM = NULL WHERE RTRIM(LTRIM(IM)) = ''
UPDATE	CLIENTES SET IE = NULL WHERE RTRIM(LTRIM(IE)) = ''
UPDATE	CLIENTES SET CONTATO = NULL WHERE RTRIM(LTRIM(CONTATO)) = ''
UPDATE	CLIENTES SET FANTASIA = NULL WHERE RTRIM(LTRIM(FANTASIA)) = ''
GO


UPDATE	CLIENTES SET CIDADE = RTRIM(LTRIM(CIDADE))
UPDATE	CLIENTES SET CIDADE_COB = RTRIM(LTRIM(CIDADE_COB))
GO

UPDATE CLIENTES SET CPF = CGC WHERE LEN(LTRIM(RTRIM(CGC))) = 11
UPDATE CLIENTES SET CNPJ = CGC WHERE LEN(LTRIM(RTRIM(CGC))) = 14
GO




------ CIDADES ------
INSERT INTO TBL_CIDADES( DESCCID, CODESTADO )
	SELECT 'NAO ESPECIFICADO', 'MG'
GO

INSERT INTO TBL_CIDADES( DESCCID, CODESTADO )
	SELECT 	DISTINCT CIDADE, ISNULL(ESTADO, 'MG')
	FROM 	CLIENTES
	WHERE	COD NOT IN (
				SELECT 	DISTINCT COD
				FROM 	CLIENTES
						INNER JOIN TBL_CIDADES
						ON CLIENTES.CIDADE = TBL_CIDADES.DESCCID
						AND CLIENTES.ESTADO = TBL_CIDADES.CODESTADO ) 
			AND CIDADE IS NOT NULL
GO
INSERT INTO TBL_CIDADES( DESCCID, CODESTADO )
	SELECT 	DISTINCT CIDADE_COB, ISNULL(ESTADO_COB, 'MG')
	FROM 	CLIENTES
	WHERE	COD NOT IN (
				SELECT 	COD
				FROM 	CLIENTES
						INNER JOIN TBL_CIDADES
						ON CLIENTES.CIDADE_COB = TBL_CIDADES.DESCCID
						AND CLIENTES.ESTADO_COB = TBL_CIDADES.CODESTADO ) 
			AND CIDADE_COB IS NOT NULL
GO

------ TIPOS DE LOGRADOURO ------

ALTER TABLE CLIENTES
	ADD ENDERECO_TMP NVARCHAR(100) NULL
GO
ALTER TABLE CLIENTES
	ADD ENDERECO_COB_TMP NVARCHAR(100) NULL
GO





UPDATE CLIENTES SET ENDERE = REPLACE(ENDERE, 'PRAÞA', 'PRAÇA')
GO
UPDATE CLIENTES SET ENDERE_COB = REPLACE(ENDERE_COB, 'PRAÞA', 'PRAÇA')
GO
UPDATE CLIENTES SET TIPO = REPLACE(TIPO, 'PRAÞA', 'PRAÇA')
GO
UPDATE CLIENTES SET TIPO_COB = REPLACE(TIPO_COB, 'PRAÞA', 'PRAÇA')
GO

UPDATE CLIENTES SET ENDERE = REPLACE(ENDERE, 'R.', 'RUA')
GO
UPDATE CLIENTES SET ENDERE_COB = REPLACE(ENDERE_COB, 'R.', 'RUA')
GO
UPDATE CLIENTES SET TIPO = REPLACE(TIPO, 'R.', 'RUA')
GO
UPDATE CLIENTES SET TIPO_COB = REPLACE(TIPO_COB, 'R.', 'RUA')
GO

UPDATE CLIENTES SET ENDERE = REPLACE(ENDERE, 'AV.', 'AVENIDA')
GO
UPDATE CLIENTES SET ENDERE_COB = REPLACE(ENDERE_COB, 'AV.', 'AVENIDA')
GO
UPDATE CLIENTES SET TIPO = REPLACE(TIPO, 'AV.', 'AVENIDA')
GO
UPDATE CLIENTES SET TIPO_COB = REPLACE(TIPO_COB, 'AV.', 'AVENIDA')
GO



UPDATE CLIENTES SET TIPO = 'OUTROS' WHERE TIPO IS NULL
GO
UPDATE CLIENTES SET TIPO_COB = 'OUTROS' WHERE TIPO_COB IS NULL
GO

UPDATE CLIENTES SET TIPO = RTRIM(LTRIM(TIPO))
GO
UPDATE CLIENTES SET TIPO_COB = RTRIM(LTRIM(TIPO_COB))
GO


INSERT INTO TBL_TIPOS_LOGRADOURO
	SELECT DISTINCT TIPO FROM CLIENTES WHERE TIPO NOT IN( SELECT DISTINCT DESCTIPOLOGRADOURO FROM TBL_TIPOS_LOGRADOURO ) AND TIPO IS NOT NULL
GO
INSERT INTO TBL_TIPOS_LOGRADOURO
	SELECT DISTINCT TIPO_COB FROM CLIENTES WHERE TIPO_COB NOT IN( SELECT DISTINCT DESCTIPOLOGRADOURO FROM TBL_TIPOS_LOGRADOURO ) AND TIPO_COB IS NOT NULL
GO




**************



SELECT ENDERE FROM CLIENTES WHERE 



UPDATE CLIENTES SET ENDERECO_TMP = ENDERE
UPDATE CLIENTES SET ENDERECO_COB_TMP = ENDERE_COB
GO


UPDATE CLIENTES SET TIPO = 'ALAMEDA' WHERE ENDERECO_TMP LIKE 'ALAMEDA%'
UPDATE CLIENTES SET TIPO = 'AVENIDA' WHERE ENDERECO_TMP LIKE 'AVENIDA%'
UPDATE CLIENTES SET TIPO = 'CAMPO' WHERE ENDERECO_TMP LIKE 'CAMPO%'
UPDATE CLIENTES SET TIPO = 'FAZENDA' WHERE ENDERECO_TMP LIKE 'FAZENDA%'
UPDATE CLIENTES SET TIPO = 'PRAÇA' WHERE ENDERECO_TMP LIKE 'PRAÇA%'
UPDATE CLIENTES SET TIPO = 'RECANTO' WHERE ENDERECO_TMP LIKE 'RECANTO%'
UPDATE CLIENTES SET TIPO = 'RODOVIA' WHERE ENDERECO_TMP LIKE 'RODOVIA%'
UPDATE CLIENTES SET TIPO = 'RUA' WHERE ENDERECO_TMP LIKE 'RUA%'
UPDATE CLIENTES SET TIPO = 'TRAVESSA' WHERE ENDERECO_TMP LIKE 'TRAVESSA%'
UPDATE CLIENTES SET TIPO = 'VIA' WHERE ENDERECO_TMP LIKE 'VIA%'
GO
UPDATE CLIENTES SET TIPO_COB = 'ALAMEDA' WHERE ENDERECO_COB_TMP LIKE 'ALAMEDA%'
UPDATE CLIENTES SET TIPO_COB = 'AVENIDA' WHERE ENDERECO_COB_TMP LIKE 'AVENIDA%'
UPDATE CLIENTES SET TIPO_COB = 'CAMPO' WHERE ENDERECO_COB_TMP LIKE 'CAMPO%'
UPDATE CLIENTES SET TIPO_COB = 'FAZENDA' WHERE ENDERECO_COB_TMP LIKE 'FAZENDA%'
UPDATE CLIENTES SET TIPO_COB = 'PRAÇA' WHERE ENDERECO_COB_TMP LIKE 'PRAÇA%'
UPDATE CLIENTES SET TIPO_COB = 'RECANTO' WHERE ENDERECO_COB_TMP LIKE 'RECANTO%'
UPDATE CLIENTES SET TIPO_COB = 'RODOVIA' WHERE ENDERECO_COB_TMP LIKE 'RODOVIA%'
UPDATE CLIENTES SET TIPO_COB = 'RUA' WHERE ENDERECO_COB_TMP LIKE 'RUA%'
UPDATE CLIENTES SET TIPO_COB = 'TRAVESSA' WHERE ENDERECO_COB_TMP LIKE 'TRAVESSA%'
UPDATE CLIENTES SET TIPO_COB = 'VIA' WHERE ENDERECO_COB_TMP LIKE 'VIA%'
GO


UPDATE CLIENTES SET ENDERECO_TMP = RTRIM(LTRIM(REPLACE(ENDERECO_TMP, TIPO, '')))
UPDATE CLIENTES SET ENDERECO_COB_TMP = RTRIM(LTRIM(REPLACE(ENDERECO_COB_TMP, TIPO_COB, '')))
GO





------ BAIRROS ------
UPDATE CLIENTES SET COMPLE = REPLACE(COMPLE, 'COREGO', '')
UPDATE CLIENTES SET COMPLE_COB = REPLACE(COMPLE, 'COREGO', '')
GO

UPDATE CLIENTES SET COMPLE = RTRIM(LTRIM(COMPLE))
UPDATE CLIENTES SET COMPLE_COB = RTRIM(LTRIM(COMPLE_COB))
GO




INSERT INTO TBL_BAIRROS
	SELECT 'NAO ESPECIFICADO'
GO
INSERT INTO TBL_BAIRROS
	SELECT DISTINCT COMPLE FROM CLIENTES WHERE COMPLE NOT IN( SELECT DISTINCT DESCBAI FROM TBL_BAIRROS ) AND COMPLE IS NOT NULL
GO

INSERT INTO TBL_BAIRROS
	SELECT DISTINCT COMPLE_COB FROM CLIENTES WHERE COMPLE_COB NOT IN( SELECT DISTINCT DESCBAI FROM TBL_BAIRROS ) AND COMPLE_COB IS NOT NULL
GO

------ TIPOLOGIAS ------
INSERT INTO TBL_TIPOLOGIAS( CODTIPOLOGIA, DESCTIPOLOGIA, VENDERPRODCONTROLADO ) VALUES( '001', 'OUTROS', 0 )
GO

------ CLIENTES ------
--ALTER TABLE TBL_CLIENTES
--	ADD COD_IMPORTACAO_TEMP INT NULL
GO

/*
INSERT INTO TBL_PRODUTOS_TIPOS_TABELA(CODTIPOTABELA, DESCTIPOTABELA)
	SELECT 1, 'TABELA GERAL'
GO
*/



UPDATE CLIENTES SET ENDERECO_TMP = RTRIM(LTRIM(LEFT(ENDERECO_TMP, 30)))
UPDATE CLIENTES SET ENDERECO_COB_TMP = RTRIM(LTRIM(LEFT(ENDERECO_COB_TMP, 30)))

UPDATE CLIENTES SET CMPL = RTRIM(LTRIM(LEFT(CMPL, 10)))
UPDATE CLIENTES SET CMPL_COB = RTRIM(LTRIM(LEFT(CMPL_COB, 10)))

UPDATE CLIENTES SET FONE = RTRIM(LTRIM(LEFT(FONE, 12)))
UPDATE CLIENTES SET FAX = RTRIM(LTRIM(LEFT(FAX, 12)))

UPDATE CLIENTES SET OBS = RTRIM(LTRIM(OBS))
UPDATE CLIENTES SET OBS = NULL WHERE RTRIM(LTRIM(OBS)) = ''

UPDATE CLIENTES SET CEP = '0' WHERE CEP IS NULL
UPDATE CLIENTES SET CEP_COB = '0' WHERE CEP_COB IS NULL

UPDATE CLIENTES SET ENDERECO_TMP = 'NENHUM' WHERE ENDERECO_TMP IS NULL
UPDATE CLIENTES SET ENDERECO_COB_TMP = 'NENHUM' WHERE ENDERECO_COB_TMP IS NULL

UPDATE CLIENTES SET NUMERO = 'NA' WHERE NUMERO IS NULL
UPDATE CLIENTES SET NUMERO_COB = 'NA' WHERE NUMERO_COB IS NULL

UPDATE CLIENTES SET ESTADO = 'MG' WHERE ESTADO IS NULL

UPDATE CLIENTES SET FANTASIA = RTRIM(LTRIM(LEFT(NOME, 40))) WHERE FANTASIA IS NULL

UPDATE CLIENTES SET ESTADO = 'GO' WHERE CIDADE = 'BRASILIA'
UPDATE CLIENTES SET ESTADO = 'MG' WHERE CIDADE = 'BELO HORIZONTE'
UPDATE CLIENTES SET ESTADO = 'MG' WHERE CIDADE = 'GOVERNADOR VALADARES'
UPDATE CLIENTES SET ESTADO = 'MG' WHERE ESTADO IN( 'MF', 'MH' )
UPDATE CLIENTES SET ESTADO = 'MG', CIDADE = 'GOVERNADOR VALADARES' WHERE ESTADO = 'G ' AND CIDADE IS NULL
UPDATE CLIENTES SET ESTADO = 'RJ' WHERE ESTADO = 'RG'
UPDATE CLIENTES SET ESTADO = RTRIM(LTRIM(ESTADO))
UPDATE CLIENTES SET CIDADE = RTRIM(LTRIM(CIDADE))

INSERT TBL_ESTADOS (CODESTADO, DESCESTADO) VALUES('RR', 'RORAIMA')
GO



INSERT INTO TBL_CLIENTES ( [RAZAO], [LOGRADOURO], [NUMERO], [COMPLEMENTO], [CEP], [NUMEROCOB], [COMPLECOB], [CEPCOB], [TELEFONE], [FAX], [EMAIL], [LIMITECRED], [DTPRICOMPRA], [VALPRICOMPRA], [MAIORATRASO], [OBSERVACAO], [DTCADASTRO], [CNPJ], [CPF], [LOGRADOUROCOB], [HOMEPAGE], [DESATIVADO], [TIPOCLI], [EMITIUCARTA1], [CODBAI], [DESCTIPOLOGRADOURO], [CODESTADO], [CODCID], [CODTIPOLOGIA], [DESCTIPOLOGRADOURO_1], [CODESTADO_1], [CODCID_1], [CODBAI_1], [CODROTA], [DTCARTACOBRANCA], [DTCARTACOBRANCAANT], [MODELOCARTACOBRANCA], [MODELOCARTACOBRANCAANT], [CODEMPASSOC], [PRAZO], [DESCFORMA], [CODCOMISSIONADO2], [CODCOND], [CODBANCO], [CONTABANCARIA], [COBRARSEGURO], [ALVARASUS], [CODTIPOTABELA], [CREDENCIADO], [OBSERVACAOVENDA], [CALCULARSUBSTITUICAO], [CONCEDERDESCONTOST], [DTVALIDADEALVARA], [ALTERARTIPOTABELA], [BLOQUEADO], [TELEFONEPREVENDA1], [TELEFONEPREVENDA2], [TELEFONEPREVENDA3], [CONTATOPREVENDA1], [CONTATOPREVENDA2], [CONTATOPREVENDA3], [SHELFLIFECLIENTE], [CodEmpresaCli], [OBSPEDIDO], [OBSNOTA], [SEMEMAILPARANFE], COD_IMPORTACAO_TEMP )
	SELECT 	FANTASIA, ENDERECO_TMP, NUMERO, 
			CMPL AS [COMPLEMENTO], CEP AS [CEP], ISNULL(ISNULL(NUMERO_COB, NUMERO), 'S/N') AS [NUMEROCOB], 
			CMPL_COB AS [COMPLECOB], ISNULL(ISNULL(CEP_COB, CEP), '0') AS [CEPCOB], 
			FONE AS [TELEFONE], FAX AS [FAX], EMAIL AS [EMAIL], CREDITO AS [LIMITECRED], 			
			ISNULL( CAST(CAST(CADASTRO AS DATETIME) AS SMALLDATETIME), '01/01/1900' ) AS [DTPRICOMPRA], 
			0. AS [VALPRICOMPRA], NULL AS [MAIORATRASO], 
			OBS AS [OBSERVACAO], 			
			ISNULL( CAST(CAST(CADASTRO AS DATETIME) AS SMALLDATETIME), '01/01/1900' ) AS [DTCADASTRO], 
			[CNPJ], [CPF], ISNULL(ISNULL(ENDERECO_COB_TMP, ENDERECO_TMP), 'S/N') AS [LOGRADOUROCOB], 
			NULL AS [HOMEPAGE], (CASE WHEN ATIVO = 1 THEN 0 ELSE 1 END) AS [DESATIVADO], 
			(CASE WHEN CNPJ IS NULL THEN 'J' ELSE 'F' END) AS [TIPOCLI], 1 AS [EMITIUCARTA1], 
			IsNull( (SELECT TOP 1 CODBAI FROM TBL_BAIRROS WHERE DESCBAI = CLIENTES.COMPLE), 1 ) AS [CODBAI], 
			TIPO AS [DESCTIPOLOGRADOURO], ESTADO AS [CODESTADO], 
			(SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = ISNULL(CLIENTES.CIDADE, 'NAO ESPECIFICADO')) AS [CODCID], 
			'001' AS [CODTIPOLOGIA], ISNULL(TIPO_COB, TIPO) AS [DESCTIPOLOGRADOURO_1],
			ISNULL(ESTADO_COB, ESTADO) AS [CODESTADO_1], 
			(SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = ISNULL(CLIENTES.CIDADE_COB, 'NAO ESPECIFICADO')) AS [CODCID_1], 
			(SELECT TOP 1 CODBAI FROM TBL_BAIRROS WHERE DESCBAI = ISNULL(CLIENTES.COMPLE_COB, 'NAO ESPECIFICADO')) AS [CODBAI_1], 
			NULL AS [CODROTA], NULL AS [DTCARTACOBRANCA], NULL AS [DTCARTACOBRANCAANT], NULL AS [MODELOCARTACOBRANCA], 
			NULL AS [MODELOCARTACOBRANCAANT], NULL AS [CODEMPASSOC], 0 AS [PRAZO], 'DINHEIRO' AS [DESCFORMA], 
			NULL AS [CODCOMISSIONADO2], '00' AS [CODCOND], NULL AS [CODBANCO], NULL AS [CONTABANCARIA], 
			0 AS [COBRARSEGURO], NULL AS [ALVARASUS], 1 AS [CODTIPOTABELA], 0 AS [CREDENCIADO], 
			NULL AS [OBSERVACAOVENDA], 0 AS [CALCULARSUBSTITUICAO], 
			0 AS [CONCEDERDESCONTOST], 
			NULL AS [DTVALIDADEALVARA], 0 AS [ALTERARTIPOTABELA], 0 AS [BLOQUEADO], NULL AS [TELEFONEPREVENDA1], 
			NULL AS [TELEFONEPREVENDA2], NULL AS [TELEFONEPREVENDA3], 
			NULL AS [CONTATOPREVENDA1], NULL AS [CONTATOPREVENDA2], NULL AS [CONTATOPREVENDA3], 
			0 AS [SHELFLIFECLIENTE], NULL AS [CodEmpresaCli], NULL AS [OBSPEDIDO], NULL AS [OBSNOTA], 
			0 AS [SEMEMAILPARANFE], COD AS COD_IMPORTACAO_TEMP
	FROM 	CLIENTES AS CLIENTES
GO




------ CLIJUR ------
INSERT INTO TBL_CLIJUR( [CODEMP], [FANTASIA], [INSCESTAD] )
	SELECT 	TBL_CLIENTES.CODEMP, 
			ISNULL( RTRIM(LTRIM(FANTASIA)), NOME ) AS FANTASIA,
			IE AS [INSCESTAD]
	FROM 	CLIENTES
			INNER JOIN TBL_CLIENTES
			ON TBL_CLIENTES.COD_IMPORTACAO_TEMP = CLIENTES.COD
	WHERE	TBL_CLIENTES.CNPJ IS NOT NULL
GO

------ CLIFIS ------
INSERT INTO TBL_CLIFIS ( [CODEMP], [PAI], [MAE], [DTNASC], [CONJUGE], [EMPTRAB] )
	SELECT 	TBL_CLIENTES.CODEMP, 
			[PAI], [MAE], RIGHT(LEFT(DATANAS, 5), 2) + '/' + LEFT(DATANAS, 2) + '/' + RIGHT(DATANAS, 4) AS [DTNASC], 
			[CONJUGE], PROFISSAO AS [EMPTRAB]
	FROM 	CLIENTES
			INNER JOIN TBL_CLIENTES
			ON TBL_CLIENTES.COD_IMPORTACAO_TEMP = CLIENTES.COD
	WHERE	TBL_CLIENTES.CPF IS NOT NULL
GO




















UPDATE ESTOQUE SET MEDIDA = UPPER(RTRIM(LTRIM(MEDIDA)))
UPDATE ESTOQUE SET DESCRICAO = UPPER(RTRIM(LTRIM(DESCRICAO)))
UPDATE ESTOQUE SET REFERENCIA = UPPER(RTRIM(LTRIM(REFERENCIA)))
UPDATE ESTOQUE SET NOME = UPPER(RTRIM(LTRIM(NOME)))
UPDATE ESTOQUE SET FORNECEDOR = UPPER(RTRIM(LTRIM(FORNECEDOR)))
UPDATE ESTOQUE SET FORNEC_PRE = UPPER(RTRIM(LTRIM(FORNEC_PRE)))
UPDATE ESTOQUE SET NCM = UPPER(RTRIM(LTRIM(NCM)))

UPDATE ESTOQUE SET MEDIDA = NULL WHERE MEDIDA = ''
UPDATE ESTOQUE SET DESCRICAO = NULL WHERE DESCRICAO = ''
UPDATE ESTOQUE SET REFERENCIA = NULL WHERE REFERENCIA = ''
UPDATE ESTOQUE SET NOME = NULL WHERE NOME = ''
UPDATE ESTOQUE SET FORNECEDOR = NULL WHERE FORNECEDOR = ''
UPDATE ESTOQUE SET FORNEC_PRE = NULL WHERE FORNEC_PRE = ''
UPDATE ESTOQUE SET NCM = NULL WHERE NCM = ''
GO

------ TIPO UNIDADE ------
INSERT INTO TBL_TIPOS_UNIDADE
	SELECT DISTINCT MEDIDA, MEDIDA FROM ESTOQUE
GO

------ GRUPOS ------
INSERT INTO TBL_GRUPOS(DESCGRUPO)
	SELECT 'NAO ESPECIFICADO'
GO
INSERT INTO TBL_GRUPOS(DESCGRUPO)
	SELECT DISTINCT NOME FROM ESTOQUE WHERE NOME IS NOT NULL
GO


------ LINHAS ------
DECLARE @TBL_TEMP TABLE( COD INT NOT NULL IDENTITY(1,1), DESCRICAO NVARCHAR(15) )

INSERT INTO @TBL_TEMP
	SELECT 'NAO ESPEC.'

INSERT INTO @TBL_TEMP
	SELECT DISTINCT NOME FROM ESTOQUE WHERE NOME IS NOT NULL

DELETE FROM TBL_LINHAS

INSERT INTO TBL_LINHAS(CODLINHA, DESCLINHA)
	SELECT * FROM @TBL_TEMP
GO

------ PRODUTOS ------
ALTER TABLE TBL_PRODUTOS
	ADD COD_IMPORTACAO_TEMP INT NULL
GO

INSERT INTO TBL_PRODUTOS ( [DESCPROD], [CODBARRA], [CODFABRICA], [PESO], [CONTROLARGRADE], [CODTIPOUNIDADE], [CODGRUPO], [CODEMP], [CODPRODNCM], [UNIDADECALCULO], [PESOVARIAVEL], [UNIDADEESTOQUE], [PRINCIPIOATIVO], [INSTRUCOES], [LISTA], [CONTROLADO], [SHELFLIFEDIAS], [DIRECIONADODIAS], [CONTROLARVALIDADE], [CODLINHA], [SERVICO], [PESOEMBALAGEM], [PESOBRUTO], [CODPRODDCB], [PRODUCAOESTOQUE], [CODTIPODOITEM], COD_IMPORTACAO_TEMP )
	SELECT 	DESCRICAO AS [DESCPROD], NULL AS [CODBARRA], NULL AS [CODFABRICA], [PESO], 
			0 AS [CONTROLARGRADE], MEDIDA AS [CODTIPOUNIDADE], 
			(SELECT TOP 1 CODGRUPO FROM TBL_GRUPOS WHERE DESCGRUPO = ISNULL(ESTOQUE.NOME, 'NAO ESPECIFICADO') ) AS [CODGRUPO], 
			NULL AS [CODEMP], 
			( SELECT TOP 1 CODPRODNCM FROM TBL_PRODUTOS_NCM WHERE CODPRODNCM = ESTOQUE.NCM ) AS [CODPRODNCM], 
			(CASE WHEN MEDIDA = 'KG' THEN 'K' ELSE 'U' END) AS [UNIDADECALCULO], 
			0 AS [PESOVARIAVEL], (CASE WHEN MEDIDA = 'KG' THEN 'K' ELSE 'U' END) AS [UNIDADEESTOQUE], 
			NULL AS [PRINCIPIOATIVO], NULL AS [INSTRUCOES], NULL AS [LISTA], 0 AS [CONTROLADO], 
			0 AS [SHELFLIFEDIAS], 0 AS [DIRECIONADODIAS], 0 AS [CONTROLARVALIDADE], 
			(SELECT TOP 1 CODLINHA FROM TBL_LINHAS WHERE DESCLINHA = ISNULL(ESTOQUE.NOME, 'NAO ESPEC.') ) AS [CODLINHA], 
			0 AS [SERVICO], NULL AS [PESOEMBALAGEM], 0. AS [PESOBRUTO], NULL AS [CODPRODDCB], 
			NULL AS [PRODUCAOESTOQUE], NULL AS [CODTIPODOITEM], CAST(CODIGO AS INT) AS COD_IMPORTACAO_TEMP
	FROM 	ESTOQUE AS ESTOQUE
GO




INSERT INTO TBL_PRODUTOS_EMPRESA ( [CODEMPRESA], [CODPROD], [ESTOQUE], [ESTOQUEDISP], [ESTOQUEMIN], [ESTOQUEMAX], [PRCUSTO], [PRCUSTOPEDIDO], [PRMEDIO], [PRCUSTOCOMICMS], [PRUNIT], [CODALICMS], [ALICMSSAI], [ALICMSENT], [BCRENT], [BCRSAI], [ESTOQUEANT], [ESTOQUEDISPANT], [PRCUSTOANT], [PRMEDIOANT], [DESATIVADO], [CODSITTRIBENT], [CODSITTRIBSAI], [IPIENT], [IPISAI], [DATAULTCUSTO], [DESCLOCALIZACAO], [PRODUTOACABADO], [ACEITARDESCONTO], [IMPRIMEINVENTARIOFISCAL], [PRVENDATABELAPRECOS], [DIVISOR], [EMBALAGEM], [CAIXASPORCAMADA], [CAIXASPORPALLET], [TABELA], [INDUSTRIALIZADO], [VALORICMSSUBSENT], [NAOAGRUPAR], [NUMCONTACONTABIL], [ENVIARPARAPALM], [ORIGEMMERCADORIA], [CODSITTRIBIPISAI], [CODSITTRIBIPIENT] )
	SELECT 	2 AS CODEMPRESA, CODPROD, QTD_ATUAL AS [ESTOQUE], QTD_ATUAL AS [ESTOQUEDISP], QTD_MINIM AS [ESTOQUEMIN], 
			NULL AS [ESTOQUEMAX], PRECO AS [PRCUSTO], CUSTOCOMPR AS [PRCUSTOPEDIDO], CUSTOMEDIO AS [PRMEDIO], 
			0. AS [PRCUSTOCOMICMS], PRECO AS [PRUNIT], NULL AS [CODALICMS], 0. AS [ALICMSSAI], 0. AS [ALICMSENT], 
			0. AS [BCRENT], 0. AS [BCRSAI], 0. AS [ESTOQUEANT], 0. AS [ESTOQUEDISPANT], 0. AS [PRCUSTOANT], 
			0. AS [PRMEDIOANT], (CASE WHEN ATIVO = 1 THEN 0 ELSE 1 END) AS [DESATIVADO], CST AS [CODSITTRIBENT], 
			CST AS [CODSITTRIBSAI], IPI AS [IPIENT], IPI AS [IPISAI], NULL AS [DATAULTCUSTO], NULL AS [DESCLOCALIZACAO], 
			1 AS [PRODUTOACABADO], 0 AS [ACEITARDESCONTO], 0 AS [IMPRIMEINVENTARIOFISCAL], NULL AS [PRVENDATABELAPRECOS], 
			1 AS [DIVISOR], NULL AS [EMBALAGEM], 1 AS [CAIXASPORCAMADA], 1 AS [CAIXASPORPALLET], 
			1 AS [TABELA], 
			0. AS [INDUSTRIALIZADO], 0. AS [VALORICMSSUBSENT], 1 AS [NAOAGRUPAR], NULL AS [NUMCONTACONTABIL], 
			0 AS [ENVIARPARAPALM], 0 AS [ORIGEMMERCADORIA], 
			'52' AS [CODSITTRIBIPISAI], '02' AS [CODSITTRIBIPIENT]
	FROM 	ESTOQUE
			INNER JOIN TBL_PRODUTOS
			ON TBL_PRODUTOS.COD_IMPORTACAO_TEMP = CAST(ESTOQUE.CODIGO AS INT)
GO



/*   PIS E COFINS   */

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS ( TIPOOPERACAO, CODEMPRESA, CodSitTribPis, CodSitTribCofins, Pis, Cofins, CodNaturezaReceitaPis, CodNaturezaReceitaCofins, CODOBS, TIPODENOTA)
	SELECT 	DISTINCT 
			'E' AS TIPOOPERACAO, 
			2 AS CODEMPRESA, 
			Cst_Pis AS CodSitTribPis, 
			Cst_Cofins AS CodSitTribCofins, 
			Pis,
			Cofins,
			NULL AS CodNaturezaReceitaPis,
			NULL AS CodNaturezaReceitaCofins,
			NULL AS CODOBS, 0 AS TIPODENOTA
	FROM 	ESTOQUE
			INNER JOIN TBL_PRODUTOS
			ON TBL_PRODUTOS.COD_IMPORTACAO_TEMP = CAST(ESTOQUE.CODIGO AS INT)
	WHERE	Cst_Pis IS NOT NULL AND Cst_Cofins IS NOT NULL
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS ( TIPOOPERACAO, CODEMPRESA, CodSitTribPis, CodSitTribCofins, Pis, Cofins, CodNaturezaReceitaPis, CodNaturezaReceitaCofins, CODOBS, TIPODENOTA)
	SELECT 	DISTINCT 
			'S' AS TIPOOPERACAO, 
			2 AS CODEMPRESA, 
			Cst_Pis AS CodSitTribPis, 
			Cst_Cofins AS CodSitTribCofins, 
			Pis,
			Cofins,
			NULL AS CodNaturezaReceitaPis,
			NULL AS CodNaturezaReceitaCofins,
			NULL AS CODOBS, 0 AS TIPODENOTA
	FROM 	ESTOQUE
			INNER JOIN TBL_PRODUTOS
			ON TBL_PRODUTOS.COD_IMPORTACAO_TEMP = CAST(ESTOQUE.CODIGO AS INT)
	WHERE	Cst_Pis IS NOT NULL AND Cst_Cofins IS NOT NULL
GO


INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS ( CodProd, CodTributacaoPisCofins )
	SELECT 	CodProd, 
			CodTributacaoPisCofins = (	SELECT TOP 1 CodTributacaoPisCofins 
										FROM TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS 
										WHERE CodEmpresa = 2 AND TipoOperacao = 'E')
	FROM 	ESTOQUE
			INNER JOIN TBL_PRODUTOS
			ON TBL_PRODUTOS.COD_IMPORTACAO_TEMP = CAST(ESTOQUE.CODIGO AS INT)
	WHERE	Cst_Pis IS NOT NULL AND Cst_Cofins IS NOT NULL
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS ( CodProd, CodTributacaoPisCofins )
	SELECT 	CodProd, 
			CodTributacaoPisCofins = (	SELECT TOP 1 CodTributacaoPisCofins 
										FROM TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS 
										WHERE CodEmpresa = 2 AND TipoOperacao = 'S')
	FROM 	ESTOQUE
			INNER JOIN TBL_PRODUTOS
			ON TBL_PRODUTOS.COD_IMPORTACAO_TEMP = CAST(ESTOQUE.CODIGO AS INT)
	WHERE	Cst_Pis IS NOT NULL AND Cst_Cofins IS NOT NULL
GO




-------------- CORREÇÕES -----------------


UPDATE TBL_BAIRROS SET DESCBAI = UPPER(RTRIM(LTRIM(DESCBAI)))
GO

INSERT INTO TBL_GRADES ( CODEMPRESA, CODPROD, GRADE1, GRADE2, NUMLOTE, CODBARRA, ESTOQUEDISP )
	SELECT CODEMPRESA, CODPROD, CODPROD, '01/01/1900', '0', NULL, ESTOQUEDISP FROM TBL_PRODUTOS_EMPRESA
GO

UPDATE TBL_CIDADES SET DESCCID = LTRIM(RTRIM(DESCCID))
GO
UPDATE 	TBL_CLIENTES 
SET 	CODCID = (SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = 'NOVA ERA')
WHERE 	CODCID IN (SELECT CODCID FROM TBL_CIDADES WHERE DESCCID = 'NAVA ERA')
GO
UPDATE 	TBL_CLIENTES 
SET 	CODCID = (SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = 'JOAO MONLEVADE')
WHERE 	CODCID IN (SELECT CODCID FROM TBL_CIDADES WHERE DESCCID = 'JOAO MANLEVADE')
GO
UPDATE 	TBL_CLIENTES 
SET 	CODCID = (SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = 'SAO LUIS DE MONTES BELOS')
WHERE 	CODCID IN (SELECT CODCID FROM TBL_CIDADES WHERE DESCCID = 'SAA LUIS DE MANTES BELAS')
GO

UPDATE TBL_TIPOS_UNIDADE SET CODTIPOUNIDADE = RTRIM(LTRIM(CODTIPOUNIDADE))
UPDATE TBL_TIPOS_UNIDADE SET DESCTIPOUNIDADE = RTRIM(LTRIM(DESCTIPOUNIDADE))
GO

