USE MASTER
GO
USE GDATA_PNEUS_CACIQUE
GO
USE GDATA_PNEUS_CACIQUE
GO
USE GDATA_PNEUS_CACIQUE
GO

----------------------------------------------------------------------------------------------------------------- CIDADES

INSERT INTO TBL_CIDADES ( DESCCID, CODESTADO, CODCIDIBGE )
	SELECT	DISTINCT CIDADES.CID_NOME, ENDERECOS.END_UF, END_COD_MUNIC_NFE
	FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
			INNER JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
			ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
			INNER JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES
			ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
	WHERE	CIDADES.CID_NOME NOT IN ( SELECT DISTINCT DESCCID FROM TBL_CIDADES )
GO

----------------------------------------------------------------------------------------------------------------- BAIRROS

INSERT INTO TBL_BAIRROS ( DESCBAI )
	SELECT	DISTINCT ENDERECOS.END_BAIRRO
	FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
			INNER JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
			ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
			INNER JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES		
			ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
	WHERE	ENDERECOS.END_BAIRRO NOT IN ( SELECT DISTINCT DESCBAI FROM TBL_BAIRROS )
GO

----------------------------------------------------------------------------------------------------------------- LOGRADOURO

INSERT INTO TBL_TIPOS_LOGRADOURO (DESCTIPOLOGRADOURO)
	SELECT DISTINCT TIPO_LOGRADOURO FROM IMPORTACAO_CACIQUE..END_ENDERECO WHERE TIPO_LOGRADOURO NOT IN ( SELECT DESCTIPOLOGRADOURO FROM TBL_TIPOS_LOGRADOURO )
GO

----------------------------------------------------------------------------------------------------------------- CLIENTES

SET IDENTITY_INSERT TBL_CLIENTES ON
	INSERT INTO TBL_CLIENTES ( CodEmp, DTCADASTRO, DESATIVADO, EMITIUCARTA1, CodBai, CodCid, CODCID_1, CODBAI_1, PRAZO, COBRARSEGURO, CodTipoTabela, CREDENCIADO, CALCULARSUBSTITUICAO, CONCEDERDESCONTOST, ALTERARTIPOTABELA, BLOQUEADO, SHELFLIFECLIENTE, SEMEMAILPARANFE, DescontoFinanceiro, RAZAO, LOGRADOURO, NUMERO, CEP, NUMEROCOB, CEPCOB, LOGRADOUROCOB, TIPOCLI, DescTipoLogradouro, CodEstado, CodTipologia, DESCTIPOLOGRADOURO_1, CODESTADO_1, DescForma, CPF, CNPJ )
		SELECT	CLI_ID AS CodEmp, CLI_DATA_CADASTRO AS DTCADASTRO, (CASE WHEN CLI_STATUS = 'A' THEN 1 ELSE 0 END) AS DESATIVADO, 0 AS EMITIUCARTA1, 
				ISNULL( (SELECT TOP 1 CODBAI FROM TBL_BAIRROS WHERE DESCBAI = ENDERECOS.END_BAIRRO), (SELECT CODBAI FROM TBL_BAIRROS WHERE DESCBAI = 'NÃO ESPECIFICADO') ) AS CodBai, 
				ISNULL( (SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = CIDADES.CID_NOME), 1 ) AS CodCid, 
				ISNULL( (SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = CIDADES.CID_NOME), 1 ) AS CODCID_1, 
				ISNULL( (SELECT TOP 1 CODBAI FROM TBL_BAIRROS WHERE DESCBAI = ENDERECOS.END_BAIRRO), (SELECT CODBAI FROM TBL_BAIRROS WHERE DESCBAI = 'NÃO ESPECIFICADO') ) AS CODBAI_1, 
				0 AS PRAZO, 0 AS COBRARSEGURO, 1 AS CodTipoTabela, 0 AS CREDENCIADO, 0 AS CALCULARSUBSTITUICAO, 0 AS CONCEDERDESCONTOST, 0 AS ALTERARTIPOTABELA, 
				0 AS BLOQUEADO, 0 AS SHELFLIFECLIENTE, 1 AS SEMEMAILPARANFE, 0 AS DescontoFinanceiro, 
				LEFT(CLI_NOME, 45) AS RAZAO, LEFT(LOGRADOURO, 30) AS LOGRADOURO, LEFT(END_NR, 6) AS NUMERO, LEFT(END_CEP, 8) AS CEP, LEFT(END_NR, 6) AS NUMEROCOB, 
				LEFT(END_CEP, 8) AS CEPCOB, LEFT(LOGRADOURO, 30) AS LOGRADOUROCOB, LEFT(CLI_FIS_JUR, 1) AS TIPOCLI, LEFT(ISNULL(TIPO_LOGRADOURO, 'RUA'), 10) AS DescTipoLogradouro, 
				LEFT(ISNULL(ENDERECOS.END_UF, 'MG'), 2) AS CodEstado, LEFT(1, 3) AS CodTipologia, LEFT(ISNULL(TIPO_LOGRADOURO, 'RUA'), 10) AS DESCTIPOLOGRADOURO_1, 
				LEFT(ISNULL(ENDERECOS.END_UF, 'MG'), 2) AS CODESTADO_1, LEFT('DINHEIRO', 15) AS DescForma, CLI_CPF AS CPF, CLI_CNPJ AS CNPJ
		FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
				LEFT JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
				ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
				LEFT JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES		
				ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
		WHERE	CLIENTES.CLI_TCL_ID <> 2
				AND ENDERECOS.END_ID IN (	SELECT	(SELECT TOP 1 END_ID FROM IMPORTACAO_CACIQUE..END_ENDERECO WHERE END_CLI_ID = CLIENTES.CLI_ID) AS END_ID
											FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
										)
SET IDENTITY_INSERT TBL_CLIENTES OFF
GO



UPDATE	TBL_CLIENTES
SET		EMAIL = LEFT(CLI_EMAIL, 40), 
		TELEFONE = LEFT( ISNULL( ISNULL(END_TEL_CEL, END_TEL_COM), END_TEL_RES ) , 12),
		COMPLEMENTO = LEFT(END_COMPLEMENTO, 10),
		COMPLECOB = LEFT(END_COMPLEMENTO, 10)
FROM	TBL_CLIENTES
		INNER JOIN IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
		ON TBL_CLIENTES.CODEMP = CLIENTES.CLI_ID
		LEFT JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
		ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
		LEFT JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES		
		ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
WHERE	CLIENTES.CLI_TCL_ID <> 2
		AND ENDERECOS.END_ID IN (	SELECT	(SELECT TOP 1 END_ID FROM IMPORTACAO_CACIQUE..END_ENDERECO WHERE END_CLI_ID = CLIENTES.CLI_ID) AS END_ID
									FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
								)
GO



INSERT INTO TBL_CLIFIS ( CodEmp, DTNASC, IDENTIDADE )
	SELECT	CLI_ID AS CodEmp, CLI_DAT_NASC AS DTNASC, LEFT(CLI_RG, 15) AS IDENTIDADE
	FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
			LEFT JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
			ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
			LEFT JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES		
			ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
	WHERE	CLIENTES.CLI_TCL_ID <> 2
			AND ENDERECOS.END_ID IN (	SELECT	(SELECT TOP 1 END_ID FROM IMPORTACAO_CACIQUE..END_ENDERECO WHERE END_CLI_ID = CLIENTES.CLI_ID) AS END_ID
										FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
									)
			AND LEFT(CLI_FIS_JUR, 1) = 'F'
GO

INSERT INTO TBL_CLIJUR ( CodEmp, CODREGIMETRIBUTARIO, IDENTSOC1, FANTASIA, INSCESTAD)
	SELECT	CLI_ID AS CodEmp, 
			NULL AS CODREGIMETRIBUTARIO, 
			LEFT(CLI_RG, 15) AS IDENTSOC1, LEFT(CLI_NOME, 45) AS FANTASIA, 
			LEFT(CLI_INS_ESTADUAL, 17) AS INSCESTAD
	FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
			LEFT JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
			ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
			LEFT JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES		
			ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
	WHERE	CLIENTES.CLI_TCL_ID <> 2
			AND ENDERECOS.END_ID IN (	SELECT	(SELECT TOP 1 END_ID FROM IMPORTACAO_CACIQUE..END_ENDERECO WHERE END_CLI_ID = CLIENTES.CLI_ID) AS END_ID
										FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
									)
			AND LEFT(CLI_FIS_JUR, 1) = 'J'
GO

----------------------------------------------------------------------------------------------------------------- FORNECEDORES

SET IDENTITY_INSERT TBL_FORNECEDORES ON
	INSERT INTO TBL_FORNECEDORES ( CodEmp, DTCADASTRO, DESATIVADO, CodBai, CodCid, PRODUTORRURAL, SEMEMAILPARANFE, RAZAO, LOGRADOURO, NUMERO, CodEstado, CodTipologia, DescTipoLogradouro )
		SELECT	CLI_ID AS CodEmp, CLI_DATA_CADASTRO AS DTCADASTRO, (CASE WHEN CLI_STATUS = 'A' THEN 1 ELSE 0 END) AS DESATIVADO, 
				ISNULL( (SELECT TOP 1 CODBAI FROM TBL_BAIRROS WHERE DESCBAI = ENDERECOS.END_BAIRRO), (SELECT CODBAI FROM TBL_BAIRROS WHERE DESCBAI = 'NÃO ESPECIFICADO') ) AS CodBai, 
				ISNULL( (SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = CIDADES.CID_NOME), 1 ) AS CodCid, 
				0 AS PRODUTORRURAL, 0 AS SEMEMAILPARANFE, 

				LEFT(CLI_NOME, 45) AS RAZAO, LEFT(LOGRADOURO, 30) AS LOGRADOURO, LEFT(END_NR, 6) AS NUMERO, LEFT(ISNULL(ENDERECOS.END_UF, 'MG'), 2) AS CodEstado, 
				LEFT(1, 3) AS CodTipologia, LEFT(ENDERECOS.TIPO_LOGRADOURO, 10) AS DescTipoLogradouro
		FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
				LEFT JOIN IMPORTACAO_CACIQUE..END_ENDERECO AS ENDERECOS
				ON ENDERECOS.END_CLI_ID = CLIENTES.CLI_ID
				LEFT JOIN IMPORTACAO_CACIQUE..CID_CIDADE AS CIDADES		
				ON ENDERECOS.END_CID_ID = CIDADES.CID_ID
		WHERE	CLIENTES.CLI_TCL_ID = 2
				AND ENDERECOS.END_ID IN (	SELECT	(SELECT TOP 1 END_ID FROM IMPORTACAO_CACIQUE..END_ENDERECO WHERE END_CLI_ID = CLIENTES.CLI_ID) AS END_ID
											FROM	IMPORTACAO_CACIQUE..CLI_CLIENTE AS CLIENTES
										)
SET IDENTITY_INSERT TBL_FORNECEDORES OFF
GO

----------------------------------------------------------------------------------------------------------------- LINHAS

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 0, 'OUTROS' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 1, 'MOTOR' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 2, 'FREIO' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 3, 'DIREÇÃO' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 4, 'ACESSORIOS' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 5, 'SUSPENSAO' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 6, 'EMBREAGEM' )

INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
	VALUES ( 7, 'PNEUS' )

--INSERT INTO TBL_LINHAS (CodLinha, DescLinha)
--	VALUES ( 8, 'BRINDES' )
GO

----------------------------------------------------------------------------------------------------------------- GRUPOS

SET IDENTITY_INSERT TBL_GRUPOS ON
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 0,   'OUTROS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 101, 'LUBRIIFIICANTE PARA REVENDA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 102, 'FILTRO DE LUBRIFICANTE' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 103, 'FILTRO DE AR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 104, 'FILTRO DE COMBUSTIVEL' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 105, 'MOTOR DIVERSOS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 106, 'FILTRO DE AR CABINE' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 201, 'DISCO DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 202, 'PASTILHA DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 203, 'LONA DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 206, 'TAMBOR DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 207, 'FLEXÍVEL DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 209, 'SAPATA DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 210, 'FREIO DIVERSO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 211, 'CUBO DE RODA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 212, 'FLUÍDO DE FREIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 213, 'CILINDRO DE RODA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 301, 'PIVO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 302, 'TERMINAL DE DIREÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 303, 'BARRA DE DIREÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 304, 'ARTICULAÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 305, 'JUNTA HOMOCINÉTICA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 307, 'BARRA ESTABILIZADORA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 308, 'BIELETA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 309, 'KIT BARRA ESTABILIZADORA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 310, 'BRAÇO AUXILIAR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 311, 'DIREÇÃO DIVERSOS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 312, 'SETOR DE DIREÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 313, 'BUCHA BRAÇO OSCILANTE' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 314, 'BUCHA DA  BARRA ESTABILIZADORA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 315, 'BUCHA DO BRAÇO TENSOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 316, 'BUCHA DO BRAÇO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 317, 'COXIM DO DIFERENCIAL' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 318, 'BRAÇO PITMAN' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 319, 'BRAÇO OSCILANTE' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 320, 'BUCHA DA CAIXA DE DIREÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 321, 'COIFA DA CAIXA DE DIREÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 322, 'KIT BRAÇO OSCILANTE' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 323, 'COIFA DA HOMOCINÉTICA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 401, 'PALHETA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 402, 'MOLA A GÁS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 403, 'ACESSORIOS DIVERSOS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 404, 'VALVULA PARA PNEUS S/C' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 405, 'CAMARA DE AR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 501, 'AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 502, 'MOLA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 503, 'BANDEJA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 504, 'ROLAMENTO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 506, 'BUCHA DE BANDEJA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 509, 'KIT JUNTA HOMOCINÉTICA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 510, 'KIT COIFA HOMOCINETICA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 511, 'COXIM DO MOTOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 512, 'SUSPENSГO DIVERSOS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 513, 'COXIM DO AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 514, 'BATENTE DO AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 515, 'BUCHA DO AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 516, 'BUCHA DO EIXO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 517, 'COXIM DA BANDEJA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 519, 'COXIM DE APOIO DA MOLA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 522, 'COXIM DO CÂMBIO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 523, 'BUCHA DO FEIXE DE MOLA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 524, 'BUCHA DO QUADRO DO MOTOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 525, 'BUCHA DO TIRANTE' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 528, 'SUPORTE DE SUSPENSÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 530, 'BUCHA BARRA DIREÇÃO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 531, 'TERMINAL DA BARRA TENSOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 532, 'KIT FEIXE DE MOLA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 533, 'CALÇO DA MOLA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 534, 'BATENTE DA BANDEJA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 535, 'PARAFUSO DO AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 536, 'COIFA DO AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 539, 'KIT ROLAMENTO' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 541, 'BATENTE DA TRAVA' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 546, 'KIT AMORTECEDOR' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 601, 'EMBREAGEM DIVERSOS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 738, 'PNEUS PASSEIO RADIAL' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 739, 'PNEUS' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 740, 'PNEUS HIGH PERFORMANCE HP / UHP' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 741, 'PNEUS PICK-UP''S E SUV''S' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 742, 'PNEUS VANS E UTILITÁRIOS LEVES (ULT)' )
	INSERT INTO TBL_GRUPOS (CODGRUPO, DESCGRUPO) VALUES ( 862, 'BRINDES DIVERSOS' )
SET IDENTITY_INSERT TBL_GRUPOS OFF
GO

----------------------------------------------------------------------------------------------------------------- TIPOS DE UNIDADES

INSERT INTO TBL_TIPOS_UNIDADE ( CODTIPOUNIDADE, DESCTIPOUNIDADE, CODTIPOUNIDADEECF )
	SELECT DISTINCT PRO_TIPO_UNIDADE, PRO_TIPO_UNIDADE, PRO_TIPO_UNIDADE FROM IMPORTACAO_CACIQUE..PRO_PRODUTO WHERE PRO_TIPO_UNIDADE NOT IN ( SELECT CODTIPOUNIDADE FROM TBL_TIPOS_UNIDADE ) AND PRO_TIPO_UNIDADE IS NOT NULL
GO

----------------------------------------------------------------------------------------------------------------- PRODUTOS

SET IDENTITY_INSERT TBL_PRODUTOS ON
	INSERT INTO TBL_PRODUTOS ( CodProd, CONTROLARGRADE, CodGrupo, PESOVARIAVEL, CONTROLADO, SHELFLIFEDIAS, DIRECIONADODIAS, CONTROLARVALIDADE, CodLinha, SERVICO, PESOBRUTO, DescProd, CodTipoUnidade, UNIDADECALCULO, UNIDADEESTOQUE, CODBARRA, PESO, MtCubico, CodProdNcm )
		SELECT	PRO_ID AS CodProd, 0 AS CONTROLARGRADE, ISNULL(COD_GRUPO, 0) AS CodGrupo, 0 AS PESOVARIAVEL, 0 AS CONTROLADO, 0 AS SHELFLIFEDIAS, 0 AS DIRECIONADODIAS, 
				0 AS CONTROLARVALIDADE, ISNULL(COD_LINHA, 0) AS CodLinha, 0 AS SERVICO, 
				0 AS PESOBRUTO, 
				LEFT(PRO_DESCRICAO, 45) AS DescProd, LEFT(ISNULL(PRO_TIPO_UNIDADE, 'UN'), 6) AS CodTipoUnidade, LEFT('U', 1) AS UNIDADECALCULO, LEFT('U', 1) AS UNIDADEESTOQUE,
				PRO_CODIGO AS CODBARRA, 0. AS PESO, 0. AS MtCubico, PRO_CLASS_FISCAL AS CodProdNcm
		FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO
		WHERE	PRO_GPR_ID IS NOT NULL 
				AND LEN(PRO_CODIGO) <> 2
				AND CAST( PRO_GPR_ID AS INTEGER ) BETWEEN 1 AND 7
SET IDENTITY_INSERT TBL_PRODUTOS OFF
GO

----------------------------------------------------------------------------------------------------------------- ESTOQUE DE PRODUTOS

SET IDENTITY_INSERT TBL_EMPRESAS ON
	INSERT INTO TBL_EMPRESAS ( CodEmpresa, RazaoSoc, NomeFant, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, ESTADO, CEP, FONE, EMAIL, HOMEPAGE, CNPJ, INSCESTAD, OBSCUPOM, CODIMPRESSORAFISCAL, GAVETACUPOM, ENCERRACUPOM, CODCRYP, DIASCARENCIA, MOVESTOQUEORDEMPRODUCAO, DIRARQRELATO, DIRARQPEFIN, CodCid, MOVESTOQUEDISPORDEMPRODUCAO, CODREGIMETRIBUTARIO, CodContabilista, FECHARAOSALVARFRMLISTAENCERRAMENTO, ImportarNotaComNumpedNaObservacao, AcertouInventario, DirExportacaoSintegra )
		SELECT	2 AS CodEmpresa, RazaoSoc, NomeFant, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, ESTADO, CEP, FONE, EMAIL, HOMEPAGE, CNPJ, INSCESTAD, OBSCUPOM, CODIMPRESSORAFISCAL, GAVETACUPOM, ENCERRACUPOM, CODCRYP, DIASCARENCIA, MOVESTOQUEORDEMPRODUCAO, DIRARQRELATO, DIRARQPEFIN, CodCid, MOVESTOQUEDISPORDEMPRODUCAO, CODREGIMETRIBUTARIO, CodContabilista, FECHARAOSALVARFRMLISTAENCERRAMENTO, ImportarNotaComNumpedNaObservacao, AcertouInventario, DirExportacaoSintegra
		FROM	TBL_EMPRESAS
		WHERE	CodEmpresa = 1
SET IDENTITY_INSERT TBL_EMPRESAS OFF
GO

SET IDENTITY_INSERT TBL_EMPRESAS ON
	INSERT INTO TBL_EMPRESAS ( CodEmpresa, RazaoSoc, NomeFant, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, ESTADO, CEP, FONE, EMAIL, HOMEPAGE, CNPJ, INSCESTAD, OBSCUPOM, CODIMPRESSORAFISCAL, GAVETACUPOM, ENCERRACUPOM, CODCRYP, DIASCARENCIA, MOVESTOQUEORDEMPRODUCAO, DIRARQRELATO, DIRARQPEFIN, CodCid, MOVESTOQUEDISPORDEMPRODUCAO, CODREGIMETRIBUTARIO, CodContabilista, FECHARAOSALVARFRMLISTAENCERRAMENTO, ImportarNotaComNumpedNaObservacao, AcertouInventario, DirExportacaoSintegra )
		SELECT	3 AS CodEmpresa, RazaoSoc, NomeFant, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, ESTADO, CEP, FONE, EMAIL, HOMEPAGE, CNPJ, INSCESTAD, OBSCUPOM, CODIMPRESSORAFISCAL, GAVETACUPOM, ENCERRACUPOM, CODCRYP, DIASCARENCIA, MOVESTOQUEORDEMPRODUCAO, DIRARQRELATO, DIRARQPEFIN, CodCid, MOVESTOQUEDISPORDEMPRODUCAO, CODREGIMETRIBUTARIO, CodContabilista, FECHARAOSALVARFRMLISTAENCERRAMENTO, ImportarNotaComNumpedNaObservacao, AcertouInventario, DirExportacaoSintegra
		FROM	TBL_EMPRESAS
		WHERE	CodEmpresa = 1
SET IDENTITY_INSERT TBL_EMPRESAS OFF
GO

INSERT INTO TBL_PRODUTOS_EMPRESA ( CodEmpresa, CodProd, ESTOQUE, ESTOQUEDISP, DESATIVADO, COFINSENTRADA, PISSAIDA, VALORICMSSUBSENT, ENVIARPARAPALM, ORIGEMMERCADORIA, CODSITTRIBENT, CODSITTRIBSAI, CODSITTRIBIPISAI, CODSITTRIBIPIENT, ALICMSSAI, ALICMSENT, CODALICMS, PRCUSTO, PRMEDIO, PRCUSTOPEDIDO )
	SELECT	EMPRESAS.CodEmpresa, PRO_ID AS CodProd, VALORES.VLR_ESTOQUE AS ESTOQUE, VALORES.VLR_ESTOQUE AS ESTOQUEDISP, 
			(CASE WHEN PRODUTOS.PRO_INATIVO = 'SIM' THEN 1 ELSE 0 END) AS DESATIVADO, 
			0. AS COFINSENTRADA, PRO_PIS_SAIDA AS PISSAIDA, 
			0 AS VALORICMSSUBSENT, 0 AS ENVIARPARAPALM, 0 AS ORIGEMMERCADORIA, 
			LEFT(CST_ICMS_ENT, 3) AS CODSITTRIBENT, LEFT(CST_ICMS_SAI, 3) AS CODSITTRIBSAI, LEFT(CST_IPI_SAI, 2) AS CODSITTRIBIPISAI, LEFT(CST_IPI_ENT, 2) AS CODSITTRIBIPIENT,
			PRO_ICMS_SAI AS ALICMSSAI, PRO_ICMS_ENT AS ALICMSENT, PRO_ALIQ_IMP_FIS AS CODALICMS, 
			VLR_CUSTO_CONTABIL AS PRCUSTO, VLR_CUSTO_MEDIO AS PRMEDIO, PRO_PRECO2 AS PRCUSTOPEDIDO
	FROM	(SELECT CodEmpresa FROM TBL_EMPRESAS) AS EMPRESAS
			LEFT JOIN IMPORTACAO_CACIQUE..VLR_VALORES_PRODUTO AS VALORES
				ON EMPRESAS.CodEmpresa =  VALORES.VLR_EMP_ID
			LEFT JOIN IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
				ON PRODUTOS.PRO_ID = VALORES.VLR_PRO_ID
	WHERE	PRO_GPR_ID IS NOT NULL 
			AND LEN(PRO_CODIGO) <> 2
			AND CAST( PRO_GPR_ID AS INTEGER ) BETWEEN 1 AND 7
GO


----------------------------------------------------------------------------------------------------------------- IMPOSTOS IPI

-- delete from TBL_PRODUTOS_TRIBUTACAO_IPI_PARAMETROS

EXEC DropView 'IMPORTACAO_IPI'
GO

-- DROP VIEW IMPORTACAO_IPI
CREATE VIEW IMPORTACAO_IPI
AS
	SELECT	'S' AS TipoOperacao, CodEmpresa, TBL_PRODUTOS_EMPRESA.CodProd, CST_IPI_SAI AS CodSitTribIpi, 0 AS Ipi, '99' AS IpiCstDevolucao
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
			INNER JOIN TBL_PRODUTOS_EMPRESA
			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD

	UNION ALL
	
	SELECT	'E' AS TipoOperacao, CodEmpresa, TBL_PRODUTOS_EMPRESA.CodProd, CST_IPI_ENT AS CodSitTribIpi, 0 AS Ipi, '49' AS IpiCstDevolucao
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
			INNER JOIN TBL_PRODUTOS_EMPRESA
			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD
	--ORDER BY TipoOperacao, CodEmpresa, CodSitTribIpi
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_IPI_PARAMETROS ( TipoOperacao, CodEmpresa, CodSitTribIpi, Ipi, IpiCstDevolucao )
	SELECT DISTINCT TipoOperacao, CodEmpresa, CodSitTribIpi, Ipi, IpiCstDevolucao FROM IMPORTACAO_IPI
	ORDER BY TipoOperacao, CodEmpresa, CodSitTribIpi
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_IPI (CodProd, CodTributacaoIpi)
	SELECT	DISTINCT IMPORTACAO_IPI.CodProd, CodTributacaoIpi
	FROM	IMPORTACAO_IPI
			INNER JOIN TBL_PRODUTOS_TRIBUTACAO_IPI_PARAMETROS AS PARAMETROS
				ON PARAMETROS.TipoOperacao = IMPORTACAO_IPI.TipoOperacao
				AND PARAMETROS.CodEmpresa = IMPORTACAO_IPI.CodEmpresa
				AND PARAMETROS.CodSitTribIpi = IMPORTACAO_IPI.CodSitTribIpi
				AND PARAMETROS.Ipi = IMPORTACAO_IPI.Ipi
				AND PARAMETROS.IpiCstDevolucao = IMPORTACAO_IPI.IpiCstDevolucao
	--ORDER BY IMPORTACAO_IPI.CodProd, CodTributacaoIpi, IMPORTACAO_IPI.CodEmpresa
GO

EXEC DropView 'IMPORTACAO_IPI'
GO

----------------------------------------------------------------------------------------------------------------- IMPOSTOS PIS e COFINS

EXEC DropView 'IMPORTACAO_PIS_COFINS'
GO

-- DROP VIEW IMPORTACAO_PIS_COFINS
CREATE VIEW IMPORTACAO_PIS_COFINS
AS
	SELECT	'S' AS TipoOperacao, CodEmpresa, TBL_PRODUTOS_EMPRESA.CodProd, CST_PIS_SAI AS CodSitTribPis, CST_COFINS_SAI AS CodSitTribCofins, 0. AS Pis, 0. AS Cofins
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
			INNER JOIN TBL_PRODUTOS_EMPRESA
			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD

	UNION ALL
	
	SELECT	'E' AS TipoOperacao, CodEmpresa, TBL_PRODUTOS_EMPRESA.CodProd, CST_PIS_ENT AS CodSitTribPis, CST_COFINS_ENT AS CodSitTribCofins, 0. AS Pis, 0. AS Cofins
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
			INNER JOIN TBL_PRODUTOS_EMPRESA
			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD
	--ORDER BY TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS ( TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins, Pis, Cofins )
	SELECT DISTINCT TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins, Pis, Cofins FROM IMPORTACAO_PIS_COFINS
	ORDER BY TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS (CodProd, CodTributacaoPisCofins)
	SELECT	DISTINCT IMPORTACAO.CodProd, CodTributacaoPisCofins
	FROM	IMPORTACAO_PIS_COFINS AS IMPORTACAO
			INNER JOIN TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS AS PARAMETROS
				ON PARAMETROS.TipoOperacao = IMPORTACAO.TipoOperacao
				AND PARAMETROS.CodEmpresa = IMPORTACAO.CodEmpresa
				AND PARAMETROS.CodSitTribPis = IMPORTACAO.CodSitTribPis
				AND PARAMETROS.CodSitTribCofins = IMPORTACAO.CodSitTribCofins
				AND PARAMETROS.Pis = IMPORTACAO.Pis
				AND PARAMETROS.Cofins = IMPORTACAO.Cofins
	--ORDER BY IMPORTACAO_IPI.CodProd, CodTributacaoIpi, IMPORTACAO_IPI.CodEmpresa
GO

EXEC DropView 'IMPORTACAO_PIS_COFINS'
GO

----------------------------------------------------------------------------------------------------------------- IMPOSTOS ICMS
/*
EXEC DropView 'IMPORTACAO_ICMS'
GO




SELECT	CodProdTributacao, CodEstadoEmpresa, CODESTADODESTINO, ALICMSSUBS, MVA, ALICMSSAI, CODSITTRIBSAI, BCR, CodObs, CodEmpresa, COMPARARPMCMVASUBS, 
		CALCULARPMCSUBS, CALCULARMVASUBS, CALCULARPMCPARAFORADAUFSUBS, TIPOOPERACAO, TipoDeNota, CalcularStSobreDesconto, MultiplicadorST, IcmsEstornoCreditoAliq, 
		CodAlIcmsEcf, IcmsCredSnAliq, IcmsStBcr, FcpAliq, IcmsAliqInterna, CalcularDifIcmsReducao 
FROM gdata_confeitaria_vitoria..TBL_PRODUTOS_TRIBUTACAO_ICMS_PARAMETROS

SELECT	PRO_ICMS_ENT, PRO_ICMS_SAI, PRO_RED_BASE1, PRO_RED_BASE2, PRO_COD_TRIB, PRO_DIF_ICMS, PRO_PERC_BASE_CALC, PRO_SUBIST_TRIB, 
		PRO_ICMS_ENT_SUBST, PRO_ICMS_SAI_SUBST, CST_ICMS_SAI, CST_ICMS_ENT, *
FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
--			INNER JOIN TBL_PRODUTOS_EMPRESA
--			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD





-- DROP VIEW IMPORTACAO_ICMS
CREATE VIEW IMPORTACAO_ICMS
AS
	SELECT	'S' AS TipoOperacao, CodEmpresa, TBL_PRODUTOS_EMPRESA.CodProd, CST_PIS_SAI AS CodSitTribPis, CST_COFINS_SAI AS CodSitTribCofins, 0. AS Pis, 0. AS Cofins
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
			INNER JOIN TBL_PRODUTOS_EMPRESA
			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD

	UNION ALL
	
	SELECT	'E' AS TipoOperacao, CodEmpresa, TBL_PRODUTOS_EMPRESA.CodProd, CST_PIS_ENT AS CodSitTribPis, CST_COFINS_ENT AS CodSitTribCofins, 0. AS Pis, 0. AS Cofins
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
			INNER JOIN TBL_PRODUTOS_EMPRESA
			ON PRODUTOS.PRO_ID = TBL_PRODUTOS_EMPRESA.CODPROD
	--ORDER BY TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS ( TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins, Pis, Cofins )
	SELECT DISTINCT TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins, Pis, Cofins FROM IMPORTACAO_ICMS
	ORDER BY TipoOperacao, CodEmpresa, CodSitTribPis, CodSitTribCofins
GO

INSERT INTO TBL_PRODUTOS_TRIBUTACAO_PISCOFINS (CodProd, CodTributacaoPisCofins)
	SELECT	DISTINCT IMPORTACAO.CodProd, CodTributacaoPisCofins
	FROM	IMPORTACAO_ICMS AS IMPORTACAO
			INNER JOIN TBL_PRODUTOS_TRIBUTACAO_PISCOFINS_PARAMETROS AS PARAMETROS
				ON PARAMETROS.TipoOperacao = IMPORTACAO.TipoOperacao
				AND PARAMETROS.CodEmpresa = IMPORTACAO.CodEmpresa
				AND PARAMETROS.CodSitTribPis = IMPORTACAO.CodSitTribPis
				AND PARAMETROS.CodSitTribCofins = IMPORTACAO.CodSitTribCofins
				AND PARAMETROS.Pis = IMPORTACAO.Pis
				AND PARAMETROS.Cofins = IMPORTACAO.Cofins
	--ORDER BY IMPORTACAO_IPI.CodProd, CodTributacaoIpi, IMPORTACAO_IPI.CodEmpresa
GO

EXEC DropView 'IMPORTACAO_ICMS'
GO
*/

----------------------------------------------------------------------------------------------------------------- PRODUTOS PREÇOS

INSERT INTO TBL_PRODUTOS_TABELAS_CALCULO ( CodTipoTabela, CodProd, CODEMPRESACOMPRA, PRVENDA ) --, COMISSAO, MRGLUCROVENDA, MRGLUCROUNIT, DESCONTO, PRPROMOCAO, DESPESAS, CODEMPRESACOMPRA, DIFERENCAPRECO, PRVENDAKIT, REAJUSTE, DTPROMOCAOINI, DTPROMOCAOFIM, CodProdTributacaoIcms )
	SELECT	1 AS CodTipoTabela, PRO_ID AS CodProd, 1 AS CODEMPRESACOMPRA, PRO_PRECO1 AS PRVENDA
	FROM	IMPORTACAO_CACIQUE..PRO_PRODUTO AS PRODUTOS
	WHERE	PRO_ID IN (SELECT CODPROD FROM TBL_PRODUTOS)
GO

----------------------------------------------------------------------------------------------------------------- COMISSIONADOS

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CIDADE = 'IPATINGA'
WHERE	FUN_CIDADE IS NULL
GO

INSERT INTO TBL_CIDADES ( DESCCID, CODESTADO, CODCIDIBGE )
	SELECT	DISTINCT FUN_CIDADE, 'MG', NULL
	FROM	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
	WHERE	FUN_CIDADE NOT IN ( SELECT DISTINCT DESCCID FROM TBL_CIDADES )
GO


INSERT INTO TBL_TIPOS_COMISSIONADO
	VALUES ('VENDEDOR')
GO

-- FINAL --

SET IDENTITY_INSERT TBL_COMISSIONADOS ON
	INSERT INTO TBL_COMISSIONADOS ( CodComissionado, DTCADASTRO, DESATIVADO, CodBai, CodCid, CodEmpresa, SUPERVISOR, PASSIVEMODE, TEMPALM, LIMITEDEBITORENTABILIDADE, COMPARTILHARCOMOUTRASEMPRESAS, NOMECOMISSIONADO, DescTipoLogradouro, CodEstado, TipoComissionado, OBSERVACAO, IDENTIDADE, CPF, LOGRADOURO, NUMERO, COMPLEMENTO, CEP, CELULAR, TELEFONE, EMAIL )
		SELECT	FUN_ID AS CodComissionado, FUN_DAT_CRI AS DTCADASTRO, 0 AS DESATIVADO, 
				ISNULL((SELECT TOP 1 CODBAI FROM TBL_BAIRROS WHERE DESCBAI = FUNCIONARIOS.FUN_BAIRRO), (SELECT CODBAI FROM TBL_BAIRROS WHERE DESCBAI = 'N/A')) AS CodBai, 
				(SELECT TOP 1 CODCID FROM TBL_CIDADES WHERE DESCCID = FUNCIONARIOS.FUN_CIDADE) AS CodCid, 
				FUN_EMP_ID AS CodEmpresa, 0 AS SUPERVISOR, 0 AS PASSIVEMODE, 0 AS TEMPALM, 
				0 AS LIMITEDEBITORENTABILIDADE, 0 AS COMPARTILHARCOMOUTRASEMPRESAS, 
				LEFT(FUN_NOME, 45) AS NOMECOMISSIONADO, LEFT(TIPO_LOGRADOURO, 10) AS DescTipoLogradouro, LEFT('MG', 2) AS CodEstado, LEFT('VENDEDOR', 15) AS TipoComissionado,
				FUN_OBS AS OBSERVACAO, LEFT(FUN_RG, 15) AS IDENTIDADE, LEFT(FUN_CPF, 11) AS CPF, LEFT(LOGRADOURO, 30) AS LOGRADOURO, LEFT(NUMERO, 6) AS NUMERO, 
				LEFT(COMPLEMENTO, 10) AS COMPLEMENTO, LEFT(FUN_CEP, 8) AS CEP, LEFT(FUN_TEL_CEL, 12) AS CELULAR, LEFT(FUN_TEL_RES, 12) AS TELEFONE, LEFT(FUN_EMAIL, 40) AS EMAIL
		FROM	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO AS FUNCIONARIOS
		WHERE	FUN_STATUS = 'A' AND FUN_EMP_ID > 0
SET IDENTITY_INSERT TBL_COMISSIONADOS OFF
GO

----------------------------------------------------------------------------------------------------------------- VEÍCULOS

SET IDENTITY_INSERT TBL_MONTADORA_VEICULOS ON
	INSERT INTO TBL_MONTADORA_VEICULOS (Id, DescMontadora)
		SELECT LMV_ID, ISNULL(LMV_MONTADORA, 'N/A') FROM IMPORTACAO_CACIQUE..LMV_LISTA_MONTADORA_VEICULO
SET IDENTITY_INSERT TBL_MONTADORA_VEICULOS OFF
GO

SET IDENTITY_INSERT TBL_MODELO_VEICULOS ON
	INSERT INTO TBL_MODELO_VEICULOS (Id, DescricaoModelo, IdMontadora)
		SELECT	DISTINCT LMO_ID AS Id, LMO_MODELO AS DescricaoModelo, LMO_LMV_ID AS IdMontadora 
		FROM	IMPORTACAO_CACIQUE..LMO_LISTA_MODELO_VEICULO
		WHERE	LMO_ID NOT IN ( 153, 173, 236, 296 ) -->> removendo itens duplicados ou com problemas de referência
SET IDENTITY_INSERT TBL_MODELO_VEICULOS OFF
GO


DELETE FROM Tbl_Produtos_Aplicacao
GO
DELETE FROM Tbl_Produtos_Aplicacao_Parametros
GO





SELECT	LMO_ID
FROM	IMPORTACAO_CACIQUE..LMO_LISTA_MODELO_VEICULO AS MODELO
		INNER JOIN IMPORTACAO_CACIQUE..LMV_LISTA_MONTADORA_VEICULO AS MONTADORA
		ON MODELO.LMO_LMV_ID = MONTADORA.LMV_ID

SELECT * FROM IMPORTACAO_CACIQUE..LMO_LISTA_MODELO_VEICULO
SELECT * FROM IMPORTACAO_CACIQUE..LMV_LISTA_MONTADORA_VEICULO




SELECT * FROM TBL_MODELO_VEICULOS
SELECT * FROM TBL_MONTADORA_VEICULOS

SELECT * FROM Tbl_Produtos_Aplicacao_Parametros
SELECT * FROM IMPORTACAO_CACIQUE..CMV_CADASTRO_MODELO_VEICULO


Id, IdModelo, AnoInicio, AnoFim, Observacao



INSERT INTO Tbl_Produtos_Aplicacao_Parametros ( IdModelo, AnoInicio, AnoFim, Observacao )
	SELECT	DISTINCT MODELO.Id AS IdModelo, 
			(CASE WHEN CMV_ANO_INI = 0 THEN NULL ELSE CMV_ANO_INI END) AS AnoInicio, 
			(CASE WHEN CMV_ANO_FIM = 0 THEN NULL ELSE CMV_ANO_FIM END) AS AnoFim, 
			CMV_OBS AS Observacao
	FROM	IMPORTACAO_CACIQUE..CMV_CADASTRO_MODELO_VEICULO AS CMV_CADASTRO_MODELO_VEICULO
			INNER JOIN TBL_MONTADORA_VEICULOS AS MONTADORA
				ON MONTADORA.Descricao = CMV_CADASTRO_MODELO_VEICULO.CMV_MONTADORA
			INNER JOIN TBL_MODELO_VEICULOS AS MODELO
				ON MODELO.Descricao = CMV_CADASTRO_MODELO_VEICULO.CMV_MODELO
				AND MODELO.IdMontadora = MONTADORA.Id
	WHERE	CMV_MODELO IS NOT NULL 
			AND CMV_MONTADORA IS NOT NULL
GO


INSERT INTO Tbl_Produtos_Aplicacao ( IdAplicacao, CodProd )
	SELECT	(	SELECT	TOP 1 Id 
				FROM	Tbl_Produtos_Aplicacao_Parametros 
				WHERE	IdModelo = INFOS.IdModelo 
						AND IsNull(AnoInicio, 0) = IsNull(INFOS.AnoInicio, 0) 
						AND IsNull(AnoFim, 0) = IsNull(INFOS.AnoFim, 0)
						AND IsNull(Observacao, '') = IsNull(INFOS.Observacao, '') 
			) AS IdAplicacao, 
			CodProd
	FROM	(	SELECT	DISTINCT PRODUTOS.CodProd, MODELO.Id AS IdModelo, 
						(CASE WHEN CMV_ANO_INI = 0 THEN NULL ELSE CMV_ANO_INI END) AS AnoInicio, 
						(CASE WHEN CMV_ANO_FIM = 0 THEN NULL ELSE CMV_ANO_FIM END) AS AnoFim, 
						CMV_OBS AS Observacao
				FROM	IMPORTACAO_CACIQUE..CMV_CADASTRO_MODELO_VEICULO AS CMV_CADASTRO_MODELO_VEICULO
						INNER JOIN TBL_MONTADORA_VEICULOS AS MONTADORA
							ON MONTADORA.Descricao = CMV_CADASTRO_MODELO_VEICULO.CMV_MONTADORA
						INNER JOIN TBL_MODELO_VEICULOS AS MODELO
							ON MODELO.Descricao = CMV_CADASTRO_MODELO_VEICULO.CMV_MODELO
							AND MODELO.IdMontadora = MONTADORA.Id
						INNER JOIN TBL_PRODUTOS AS PRODUTOS
							ON PRODUTOS.CodProd = CMV_CADASTRO_MODELO_VEICULO.CMV_PRO_ID
				WHERE	CMV_MODELO IS NOT NULL 
						AND CMV_MONTADORA IS NOT NULL
			) AS INFOS
GO




UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET COD_LINHA = CAST(PRO_GPR_ID AS INTEGER) WHERE PRO_GPR_ID IS NOT NULL AND RTRIM(LTRIM(PRO_GPR_ID)) <> ''
UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET COD_GRUPO = CAST(PRO_SPR_ID AS INTEGER) WHERE PRO_SPR_ID IS NOT NULL AND RTRIM(LTRIM(PRO_SPR_ID)) <> ''
GO

UPDATE	TBL_PRODUTOS
SET		CodGrupo = PROD_PRODUTO.COD_GRUPO
FROM	TBL_PRODUTOS
		INNER JOIN IMPORTACAO_CACIQUE..PRO_PRODUTO AS PROD_PRODUTO
		ON TBL_PRODUTOS.CodProd = PROD_PRODUTO.PRO_ID
WHERE	PROD_PRODUTO.COD_GRUPO IN ( SELECT CodGrupo FROM TBL_GRUPOS )
GO

UPDATE	TBL_PRODUTOS
SET		CodLinha = PROD_PRODUTO.COD_LINHA
FROM	TBL_PRODUTOS
		INNER JOIN IMPORTACAO_CACIQUE..PRO_PRODUTO AS PROD_PRODUTO
		ON TBL_PRODUTOS.CodProd = PROD_PRODUTO.PRO_ID
WHERE	PROD_PRODUTO.COD_LINHA IN ( SELECT CodLinha FROM TBL_LINHAS )
GO

