USE MASTER
GO
USE GDATA_PNEUS_CACIQUE
GO
USE GDATA_PNEUS_CACIQUE
GO
USE GDATA_PNEUS_CACIQUE
GO

----------------------------------------------------------------------------------------------------------------- CIDADES

UPDATE	IMPORTACAO_CACIQUE..CID_CIDADE
SET		CID_NOME = RTRIM(LTRIM(REPLACE(CID_NOME, '  ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..CID_CIDADE
SET		CID_NOME = RTRIM(LTRIM(REPLACE(CID_NOME, '  ', ' ')))
GO


----------------------------------------------------------------------------------------------------------------- BAIRROS

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_LOGRADOURO = RTRIM(LTRIM(REPLACE(END_LOGRADOURO, '  ', ' '))),
		END_BAIRRO = RTRIM(LTRIM(REPLACE(END_BAIRRO, '  ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_LOGRADOURO = RTRIM(LTRIM(REPLACE(END_LOGRADOURO, '  ', ' '))),
		END_BAIRRO = RTRIM(LTRIM(REPLACE(END_BAIRRO, '  ', ' ')))
GO

----------------------------------------------------------------------------------------------------------------- LOGRADOURO

ALTER TABLE IMPORTACAO_CACIQUE..END_ENDERECO
	ADD LOGRADOURO VARCHAR(1000) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..END_ENDERECO
	ADD TIPO_LOGRADOURO VARCHAR(1000) NULL
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_LOGRADOURO = RTRIM(LTRIM(REPLACE(END_LOGRADOURO, '   ', ' ')))		
GO
UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_LOGRADOURO = RTRIM(LTRIM(REPLACE(END_LOGRADOURO, '  ', ' ')))		
GO

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ':', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ';', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '/', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '\', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '.', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ',', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '- ', '-')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ' -', '-')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ']', '')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '[', '')))
GO
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(3), SPACE(1))))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = ''
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = '-'
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO IS NULL
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = 'NULL'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = END_LOGRADOURO
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = 'AVENIDA ' + RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3)
WHERE	LOGRADOURO LIKE 'AV.%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RUA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'ROD.%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'ROD %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AV %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'FAZENDA'
WHERE	LOGRADOURO LIKE 'FAZENDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-2),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'R %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'RODOVIA %'
GO

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ':', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ';', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '/', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '\', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '.', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ',', ' ')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '- ', '-')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ' -', '-')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ']', '')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '[', '')))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '''', '')))
GO
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(3), SPACE(1))))
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = ''
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = '-'
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO IS NULL
UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = 'NULL'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RUA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-2),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'R-%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'RD %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AV %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIDA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-6),
		TIPO_LOGRADOURO = 'PRAÇA'
WHERE	LOGRADOURO LIKE 'PRAÇA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'PRAÇA'
WHERE	LOGRADOURO LIKE 'PÇA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'VIA'
WHERE	LOGRADOURO LIKE 'VIA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'ALAMEDA'
WHERE	LOGRADOURO LIKE 'AL %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-9),
		TIPO_LOGRADOURO = 'TRAVESSA'
WHERE	LOGRADOURO LIKE 'TRAVESSA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'CORREGO'
WHERE	LOGRADOURO LIKE 'CORREGO %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'FAZENDA'
WHERE	LOGRADOURO LIKE 'FAZENDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = '26 ' + RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AV26%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-6),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVNIDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-6),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVNIVA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENODA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIVA%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENDA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVN %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVE %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-2),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVMANOEL%'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'ESTRADA'
WHERE	LOGRADOURO LIKE 'ESTRADA %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-5),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RU''A %'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		TIPO_LOGRADOURO = 'RUA'
WHERE	TIPO_LOGRADOURO IS NULL
GO

INSERT INTO TBL_TIPOS_LOGRADOURO VALUES('ANEL')
GO

INSERT INTO TBL_TIPOS_LOGRADOURO VALUES('ESTRADA')
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-15),
		TIPO_LOGRADOURO = 'ANEL'
WHERE	LOGRADOURO LIKE 'ANEL RODOVIARIO%'
GO

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO


UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PRESIDENTE', 'PRESID')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'MINISTRO', 'MINIST')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DEPUTADO', 'DEP')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PROFESSORA', 'PROF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PROFESSOTA', 'PROF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PROFESSOR', 'PROF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'SARGENTO', 'SARG')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DOUTOR', 'DR')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'JUNIOR', 'JR')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PREFEITO', 'PREF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DESEMBARGADOR', 'DESEMB')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'INDUSTRIAS', 'IND')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'INDUSTRIA', 'IND')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'VEREADOR', 'VERE')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'RAIMUNDO', 'RAIM')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'CONJUNTO', 'CONJ')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DE ACESSO', 'ACESSO')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'JOAQUIM', 'JOAQ')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'R FRANCISCO', 'FRANCISCO')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'TEIXEIRA', 'TEIXE')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'NOGUEIRA', 'NOGUE')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'RESIDENCIAL', 'RESID')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'ESTRADA'
WHERE	LOGRADOURO LIKE 'EST %' AND LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'BR %' 
GO

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		LOGRADOURO = LEFT(LOGRADOURO, 30)
GO

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO


----------------------------------------------------------------------------------------------------------------- NÚMEROS

UPDATE IMPORTACAO_CACIQUE..END_ENDERECO SET END_NR = RTRIM(LTRIM(REPLACE(END_NR, SPACE(2), SPACE(1))))
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'S/N'
WHERE	END_NR = 'SEM NUMERO'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'BLOC F'
WHERE	END_NR = 'BLOCO F'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'BLOC 9'
WHERE	END_NR = 'BLOCO 9'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'BLOC 2'
WHERE	END_NR = 'BLOCO 2'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'BLC 61'
WHERE	END_NR = 'BLOCO 61'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'BLC 50'
WHERE	END_NR = 'BLOCO 50'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'N/A'
WHERE	END_NR IN ( '08/07/1974', 'MONE CUNHA', 'R NITEROI', 'GONZAGA', 'LIVEIRA' )
GO


----------------------------------------------------------------------------------------------------------------- ESTADOS
UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_UF = 'MG'
WHERE	END_UF = 'MM'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_UF = 'MG'
WHERE	END_UF = 'NG'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_UF = 'MG'
WHERE	END_UF IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_UF = 'MG'
WHERE	END_UF = 'MH'
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_UF = 'MG'
WHERE	END_UF = ']M'
GO

----------------------------------------------------------------------------------------------------------------- CLIENTES
UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_CEP = ''
WHERE	END_CEP IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..CLI_CLIENTE
SET		CLI_DATA_CADASTRO = '01/01/1900'
WHERE	CLI_DATA_CADASTRO IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..END_ENDERECO
SET		END_NR = 'N/A'
WHERE	END_NR IS NULL
GO


UPDATE	IMPORTACAO_CACIQUE..CLI_CLIENTE
SET		CLI_NOME = RTRIM(LTRIM(REPLACE(CLI_NOME, '   ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..CLI_CLIENTE
SET		CLI_NOME = RTRIM(LTRIM(REPLACE(CLI_NOME, '  ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..CLI_CLIENTE
SET		CLI_NOME = RTRIM(LTRIM(REPLACE(CLI_NOME, '\', '|')))
GO
UPDATE	IMPORTACAO_CACIQUE..CLI_CLIENTE
SET		CLI_NOME = RTRIM(LTRIM(REPLACE(CLI_NOME, '/', '|')))
GO

----------------------------------------------------------------------------------------------------------------- PRODUTOS

UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET PRO_DESCRICAO = RTRIM(LTRIM(  REPLACE( PRO_DESCRICAO, SPACE(2), SPACE(1) )  ))
GO
UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET PRO_DESCRICAO = RTRIM(LTRIM(  REPLACE( PRO_DESCRICAO, SPACE(2), SPACE(1) )  ))
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'AMORTECEDORES', 'AMORT' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'AMORTECEDOR', 'AMORT' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'PASTILHAS', 'PAST' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'PASTILHA', 'PAST' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'ESTABILIZADORAS', 'ESTAB' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'ESTABILIZADORA', 'ESTAB' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'CONVENCIONAL', 'CONVENC' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'TRASEIRO', 'TRAS' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'LUBRIFICANTE', 'LUBRIF' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'HOMOCINETICA', 'HOMOCIN' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'CONDICIONADO', 'CONDIC' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'ACESSORIO', 'ACESS' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'BALANCEADOR', 'BALANC' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, 'TERMINAL', 'TERM' )
WHERE	LEN(PRO_DESCRICAO) > 45
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		PRO_DESCRICAO = REPLACE( PRO_DESCRICAO, '/PNEUS', 'PNEUS' )
WHERE	PRO_DESCRICAO LIKE '/PNEUS%'
GO

UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET PRO_DESCRICAO = RTRIM(LTRIM(  REPLACE( PRO_DESCRICAO, SPACE(2), SPACE(1) )  ))
GO
UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET PRO_DESCRICAO = RTRIM(LTRIM(  REPLACE( PRO_DESCRICAO, SPACE(2), SPACE(1) )  ))
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD COD_LINHA INT NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD COD_GRUPO INT NULL
GO

UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET COD_LINHA = CAST(PRO_GPR_ID AS INTEGER) WHERE PRO_GPR_ID IS NOT NULL AND RTRIM(LTRIM(PRO_GPR_ID)) <> ''
UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET COD_GRUPO = CAST(PRO_SPR_ID AS INTEGER) WHERE PRO_SPR_ID IS NOT NULL AND RTRIM(LTRIM(PRO_SPR_ID)) <> ''
GO



UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET COD_LINHA = 0 WHERE COD_LINHA NOT IN (SELECT CODLINHA FROM TBL_LINHAS)
UPDATE IMPORTACAO_CACIQUE..PRO_PRODUTO SET COD_GRUPO = 0 WHERE COD_GRUPO NOT IN (SELECT CODGRUPO FROM TBL_GRUPOS)
GO


----------------------------------------------------------------------------------------------------------------- ESTOQUE DE PRODUTOS
ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_IPI_SAI VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_IPI_ENT VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_PIS_SAI VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_PIS_ENT VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_COFINS_SAI VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_COFINS_ENT VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_ICMS_SAI VARCHAR(10) NULL
GO

ALTER TABLE IMPORTACAO_CACIQUE..PRO_PRODUTO
	ADD CST_ICMS_ENT VARCHAR(10) NULL
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_IPI_SAI = PRO_STI_ID_SAI
		,CST_IPI_ENT = PRO_STI_ID_ENT
		,CST_PIS_SAI = PRO_STP_ID_SAI
		,CST_PIS_ENT = PRO_STP_ID_ENT
		,CST_COFINS_SAI = PRO_STP_ID_COFINS_SAI
		,CST_COFINS_ENT = PRO_STP_ID_COFINS_ENT
		,CST_ICMS_SAI = PRO_COD_TRIB
		,CST_ICMS_ENT = PRO_COD_TRIB
GO



UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_IPI_SAI = '00'
WHERE	CST_IPI_SAI = '0'
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_IPI_ENT = '00'
WHERE	CST_IPI_ENT = '0'
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_IPI_SAI = '99'
WHERE	CST_IPI_SAI IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_IPI_ENT = '49'
WHERE	CST_IPI_ENT IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_ICMS_SAI = '041'
WHERE	CST_ICMS_SAI IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..PRO_PRODUTO
SET		CST_ICMS_ENT = '041'
WHERE	CST_ICMS_ENT IS NULL
GO




----------------------------------------------------------------------------------------------------------------- COMISSIONADOS



---- LIMPANDO LOGRADOUROS E TIPOS DE LOGRADOUROS ----
ALTER TABLE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
	ADD LOGRADOURO VARCHAR(1000) NULL
GO
ALTER TABLE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
	ADD TIPO_LOGRADOURO VARCHAR(1000) NULL
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_LOGRADOURO = RTRIM(LTRIM(REPLACE(FUN_END_LOGRADOURO, '   ', ' ')))		
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_LOGRADOURO = RTRIM(LTRIM(REPLACE(FUN_END_LOGRADOURO, '  ', ' ')))		
GO

UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ':', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ';', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '/', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '\', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '.', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ',', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '- ', '-')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ' -', '-')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ']', '')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '[', '')))
GO
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(3), SPACE(1))))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = ''
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = '-'
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO IS NULL
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = 'NULL'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = FUN_END_LOGRADOURO
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = 'AVENIDA ' + RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3)
WHERE	LOGRADOURO LIKE 'AV.%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RUA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RIUA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'ROD.%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'ROD %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AV %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'FAZENDA'
WHERE	LOGRADOURO LIKE 'FAZENDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-2),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'R %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'RODOVIA %'
GO

UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ':', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ';', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '/', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '\', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '.', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ',', ' ')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '- ', '-')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ' -', '-')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, ']', '')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '[', '')))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, '''', '')))
GO
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(3), SPACE(1))))
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = ''
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = '-'
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO IS NULL
UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = 'N/A' WHERE LOGRADOURO = 'NULL'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RUA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-2),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'R-%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'RD %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AV %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIDA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-6),
		TIPO_LOGRADOURO = 'PRAÇA'
WHERE	LOGRADOURO LIKE 'PRAÇA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'PRAÇA'
WHERE	LOGRADOURO LIKE 'PÇA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'VIA'
WHERE	LOGRADOURO LIKE 'VIA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-3),
		TIPO_LOGRADOURO = 'ALAMEDA'
WHERE	LOGRADOURO LIKE 'AL %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-9),
		TIPO_LOGRADOURO = 'TRAVESSA'
WHERE	LOGRADOURO LIKE 'TRAVESSA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'CORREGO'
WHERE	LOGRADOURO LIKE 'CORREGO %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'FAZENDA'
WHERE	LOGRADOURO LIKE 'FAZENDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = '26 ' + RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AV26%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-6),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVNIDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-6),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVNIVA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENODA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIDA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENIVA%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-7),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVENDA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVN %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVE %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-2),
		TIPO_LOGRADOURO = 'AVENIDA'
WHERE	LOGRADOURO LIKE 'AVMANOEL%'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-8),
		TIPO_LOGRADOURO = 'ESTRADA'
WHERE	LOGRADOURO LIKE 'ESTRADA %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-5),
		TIPO_LOGRADOURO = 'RUA'
WHERE	LOGRADOURO LIKE 'RU''A %'
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		TIPO_LOGRADOURO = 'RUA'
WHERE	TIPO_LOGRADOURO IS NULL
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-15),
		TIPO_LOGRADOURO = 'ANEL'
WHERE	LOGRADOURO LIKE 'ANEL RODOVIARIO%'
GO

UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO


UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PRESIDENTE', 'PRESID')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'MINISTRO', 'MINIST')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DEPUTADO', 'DEP')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PROFESSORA', 'PROF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PROFESSOTA', 'PROF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PROFESSOR', 'PROF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'SARGENTO', 'SARG')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DOUTOR', 'DR')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'JUNIOR', 'JR')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'PREFEITO', 'PREF')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DESEMBARGADOR', 'DESEMB')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'INDUSTRIAS', 'IND')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'INDUSTRIA', 'IND')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'VEREADOR', 'VERE')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'RAIMUNDO', 'RAIM')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'CONJUNTO', 'CONJ')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'DE ACESSO', 'ACESSO')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'JOAQUIM', 'JOAQ')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'R FRANCISCO', 'FRANCISCO')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'TEIXEIRA', 'TEIXE')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'NOGUEIRA', 'NOGUE')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = REPLACE(LOGRADOURO, 'RESIDENCIAL', 'RESID')
WHERE	LEN(LOGRADOURO) > 30
GO

UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = RIGHT(LOGRADOURO, LEN(LOGRADOURO)-4),
		TIPO_LOGRADOURO = 'ESTRADA'
WHERE	LOGRADOURO LIKE 'EST %' AND LEN(LOGRADOURO) > 30
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		TIPO_LOGRADOURO = 'RODOVIA'
WHERE	LOGRADOURO LIKE 'BR %' 
GO

UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		LOGRADOURO = LEFT(LOGRADOURO, 30)
GO

UPDATE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO SET LOGRADOURO = RTRIM(LTRIM(REPLACE(LOGRADOURO, SPACE(2), SPACE(1))))
GO

INSERT INTO TBL_TIPOS_LOGRADOURO (DESCTIPOLOGRADOURO)
	SELECT DISTINCT TIPO_LOGRADOURO FROM IMPORTACAO_CACIQUE..FUN_FUNCIONARIO WHERE TIPO_LOGRADOURO NOT IN ( SELECT DESCTIPOLOGRADOURO FROM TBL_TIPOS_LOGRADOURO )
GO

-----------------------------

ALTER TABLE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
	ADD NUMERO VARCHAR(1000) NULL
GO
ALTER TABLE IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
	ADD COMPLEMENTO VARCHAR(1000) NULL
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_RG = RTRIM(LTRIM(REPLACE(FUN_RG, '.', '')))		
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_RG = RTRIM(LTRIM(REPLACE(FUN_RG, '-', '')))		
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CPF = RTRIM(LTRIM(REPLACE(FUN_CPF, '.', '')))		
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CPF = RTRIM(LTRIM(REPLACE(FUN_CPF, '-', '')))		
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_RG = RTRIM(LTRIM(REPLACE(FUN_RG, '  ', ' ')))		
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CPF = RTRIM(LTRIM(REPLACE(FUN_CPF, '  ', ' ')))		
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_OBS = RTRIM(LTRIM(REPLACE(FUN_OBS, '  ', ' ')))		
GO







-- BAIRROS --
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_BAIRRO = RTRIM(LTRIM(REPLACE(FUN_BAIRRO, '  ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_BAIRRO = RTRIM(LTRIM(REPLACE(FUN_BAIRRO, '  ', ' ')))
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_BAIRRO = RTRIM(LTRIM(REPLACE(FUN_BAIRRO, 'ALIPNHO', 'ALPINHO')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_BAIRRO = RTRIM(LTRIM(REPLACE(FUN_BAIRRO, 'VIAL', 'VILA')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_BAIRRO = RTRIM(LTRIM(REPLACE(FUN_BAIRRO, 'CELLESTE', 'CELESTE')))
GO

----<><><>-----

INSERT INTO TBL_TIPOLOGIAS ( CodTipologia, DescTipologia ) VALUES (1, 'NENHUM')
GO

INSERT INTO TBL_BAIRROS (DESCBAI) VALUES ('NÃO ESPECIFICADO')
GO

INSERT INTO TBL_BAIRROS ( DESCBAI )
	SELECT	DISTINCT ENDERECOS.FUN_BAIRRO--, *
	FROM	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO AS ENDERECOS
	WHERE	ENDERECOS.FUN_BAIRRO NOT IN ( SELECT DISTINCT DESCBAI FROM TBL_BAIRROS )
GO

-- NOMES --
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_NOME = RTRIM(LTRIM(REPLACE(FUN_NOME, '  ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_NOME = RTRIM(LTRIM(REPLACE(FUN_NOME, '  ', ' ')))
GO

-- CIDADES --
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CIDADE = RTRIM(LTRIM(REPLACE(FUN_CIDADE, '  ', ' ')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CIDADE = RTRIM(LTRIM(REPLACE(FUN_CIDADE, '  ', ' ')))
GO

UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_NR = RTRIM(LTRIM(REPLACE(FUN_END_NR, ' ', '')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_NR = RTRIM(LTRIM(REPLACE(FUN_END_NR, ' ', '')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_NR = RTRIM(LTRIM(REPLACE(FUN_END_NR, ',', '/')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_NR = RTRIM(LTRIM(REPLACE(FUN_END_NR, 'AP', '/AP')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_END_NR = RTRIM(LTRIM(REPLACE(FUN_END_NR, '//', '/')))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		NUMERO = LEFT( FUN_END_NR, CAST(PATINDEX('%/%', FUN_END_NR) AS INT))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		NUMERO = REPLACE(NUMERO, '/', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		COMPLEMENTO = RIGHT(FUN_END_NR, LEN(NUMERO) + 1) 
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CEP = REPLACE(FUN_CEP, '-', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CEP = REPLACE(FUN_CEP, '.', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CEP = RTRIM(LTRIM(FUN_CEP))
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_CEP = REPLACE(FUN_CEP, '*', '')
GO


UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_CEL = REPLACE(FUN_TEL_CEL, '(', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_CEL = REPLACE(FUN_TEL_CEL, ')', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_CEL = REPLACE(FUN_TEL_CEL, '-', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_CEL = REPLACE(FUN_TEL_CEL, ' ', '')
GO


UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_RES = REPLACE(FUN_TEL_RES, '(', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_RES = REPLACE(FUN_TEL_RES, ')', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_RES = REPLACE(FUN_TEL_RES, '-', '')
GO
UPDATE	IMPORTACAO_CACIQUE..FUN_FUNCIONARIO
SET		FUN_TEL_RES = REPLACE(FUN_TEL_RES, ' ', '')
GO






























DELETE from tbl_plano_de_contas
GO

insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4',  LEFT( 'DESPESAS E CUSTOS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01',  LEFT( 'DESPESAS COM VENDAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.01',  LEFT( 'VENDA DIRETA' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.01.001',  LEFT( 'CUSTO DA MERCADORIA VENDIDA (CMV)' , 35 ),  1, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.01.002',  LEFT( 'TRANSPORTADORAS' , 35 ),  2, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.01.003',  LEFT( 'COMISSÃO DE VENDAS' , 35 ),  3, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.01.004',  LEFT( 'SPC - CONSULTA DE CREDITO' , 35 ),  4, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.01.005',  LEFT( 'CHECK CHECK - CONSULTA DE CREDITO' , 35 ),  5, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.02',  LEFT( 'VEICULOS' , 35 ), NULL, 1 )
GO
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.02.001',  LEFT( 'MOTORISTAS' , 35 ),  6, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.01.02.002',  LEFT( 'VIAGENS DO VENDEDOR' , 35 ),  7, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02',  LEFT( 'DESPESAS ADMINISTRATIVAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01',  LEFT( 'DESPESAS GERAIS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.001',  LEFT( 'COMBUSTIVEL' , 35 ),  8, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.002',  LEFT( 'CEMIG' , 35 ),  9, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.003',  LEFT( 'MATERIAL DE LIMPEZA' , 35 ),  10, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.004',  LEFT( 'MATERIAL DE ESCRITORIO E CONSUMO EM GERAL' , 35 ),  11, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.005',  LEFT( 'SERVIÇOS GERAIS' , 35 ),  12, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.006',  LEFT( 'SEGURANÇA ELETRONICA - MEG' , 35 ),  13, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.007',  LEFT( 'CONTADOR' , 35 ),  14, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.008',  LEFT( 'CORREIOS' , 35 ),  15, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.009',  LEFT( 'EXAMES - DINAMICA' , 35 ),  16, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.010',  LEFT( 'SEGURO DO ESTABELECIMENTO' , 35 ),  17, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.011',  LEFT( 'INFORMATICA - SOFTWARE' , 35 ),  18, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.012',  LEFT( 'INFORMATICA - HARDWARE' , 35 ),  19, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.013',  LEFT( 'ALUGUEL LOJA' , 35 ),  20, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.014',  LEFT( 'AGUA E ESGOTO' , 35 ),  21, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.01.070',  LEFT( 'OUTRAS DESPESAS' , 35 ),  22, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.02',  LEFT( 'TELEFONIA' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.02.001',  LEFT( 'OI TELECOMUNICAÇÕES' , 35 ),  23, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.02.002',  LEFT( 'TIM - DESPESAS PART. CEL ROGERIO.' , 35 ),  24, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.02.003',  LEFT( 'EMBRATEL' , 35 ),  25, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.03',  LEFT( 'SOCIOS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.03.001',  LEFT( 'SOCIOS - PROLABORE' , 35 ),  26, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.03.002',  LEFT( 'SOCIOS - PLANO DE SAUDE' , 35 ),  27, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.03.003',  LEFT( 'SOCIOS - SEGURO' , 35 ),  28, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.03.004',  LEFT( 'SOCIOS - CONSORCIO' , 35 ),  29, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.04',  LEFT( 'PESSOAL' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.04.001',  LEFT( 'FGTS - FUNDO DE GARANTIA' , 35 ),  30, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.04.002',  LEFT( 'FOLHA DE PAGAMENTO' , 35 ),  31, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.04.003',  LEFT( 'RESCISÃO CONTRATUAL' , 35 ),  32, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05',  LEFT( 'DESPESAS TRIBUTARIAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.001',  LEFT( 'GPS - GUIA DA PREVIDENCIA SOCIAL' , 35 ),  33, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.002',  LEFT( 'DAS - MINISTERIO DA FAZENDA' , 35 ),  34, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.003',  LEFT( 'DARF - MINISTERIO DA FAZENDA' , 35 ),  35, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.004',  LEFT( 'DAE - DOCT. DE ARRECADAÇÃO ESTADUAL' , 35 ),  36, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.005',  LEFT( 'ISS ' , 35 ),  37, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.006',  LEFT( 'IPTU' , 35 ),  38, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.007',  LEFT( 'TAXA DE LIXO' , 35 ),  39, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.05.008',  LEFT( 'PREFEITURA MUNICIPAL DE GV - TX FIS' , 35 ),  40, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06',  LEFT( 'DESPESAS FINANCEIRAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.001',  LEFT( 'IOF (BB)' , 35 ),  41, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.002',  LEFT( 'JUROS (BB)' , 35 ),  42, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.003',  LEFT( 'EMISSAO DE BOLETOS (BB)' , 35 ),  43, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.004',  LEFT( 'MANUTENÇÃO DE TITULOS (BB)' , 35 ),  44, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.005',  LEFT( 'TARIFA DESCONTO DE TITULOS (BB)' , 35 ),  45, 1 )
GO
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.006',  LEFT( 'RETORNO DE TITULO NAO PAGO (BB)' , 35 ),  46, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.06.007',  LEFT( 'CUSTODIA DE CHEQUES (BB)' , 35 ),  47, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.07',  LEFT( 'INVESTIMENTOS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.07.001',  LEFT( 'INVESTIMENTOS CURSOS E CAPACITACAO' , 35 ),  48, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.07.002',  LEFT( 'INVESTIMENTOS INFRA ESTRUTURA' , 35 ),  49, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.07.003',  LEFT( 'MARKETING & PROPAGANDA' , 35 ),  50, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.08',  LEFT( 'CONSERTOS E MANUTENCOES' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.08.001',  LEFT( 'MANUTENCAO EQUIPAMENTOS' , 35 ),  51, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.08.002',  LEFT( 'MANUTENCAO VEICULOS' , 35 ),  52, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.02.08.003',  LEFT( 'MANUTENCAO NA LOJA' , 35 ),  53, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03',  LEFT( 'PROVISÕES' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.01',  LEFT( 'PROVISÕES TRIBUTÁRIAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.01.001',  LEFT( 'PROVISÃO - IMPOSTO DE RENDA' , 35 ),  54, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.01.002',  LEFT( 'PROVISÃO - IPTU SALA XXX' , 35 ),  55, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.01.003',  LEFT( 'PROVISÃO - IPVA CAMINHÃO XXX-9999' , 35 ),  56, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.02',  LEFT( 'PROVISÕES TRABALHISTAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.02.001',  LEFT( 'PROVISÃO - 13 º SALÁRIO FUNCIONÁRIOS' , 35 ),  57, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '4.03.02.002',  LEFT( 'PROVISÃO - DE FÉRIAS FUNCIONÁRIOS' , 35 ),  58, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3',  LEFT( 'RECEITAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01',  LEFT( 'VENDAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.01',  LEFT( 'VENDAS A VISTA' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.01.001',  LEFT( 'VENDAS A VISTA EM DINHEIRO' , 35 ),  59, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.01.002',  LEFT( 'VENDAS A VISTA - CARTAO DE DEBITO' , 35 ),  60, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.01.003',  LEFT( 'VENDAS A VISTA - CHEQUE' , 35 ),  61, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.02',  LEFT( 'VENDAS A PRAZO' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.02.001',  LEFT( 'VENDAS A PRAZO - CARTAO DE CREDITO' , 35 ),  62, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.02.002',  LEFT( 'VENDAS A PRAZO - CHEQUE' , 35 ),  63, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.01.02.003',  LEFT( 'VENDA A PRAZO - NOTINHA' , 35 ),  64, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02',  LEFT( 'RECEBIMENTOS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.01',  LEFT( 'RECEBIMENTOS DE VENDAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.01.001',  LEFT( 'RECEBIMENTOS EM DINHEIRO' , 35 ),  65, 1 )
GO
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.01.002',  LEFT( 'RECEBIMENTOS EM DEPOSITO' , 35 ),  66, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.01.003',  LEFT( 'RECEBIMENTOS EM CARTAO' , 35 ),  67, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.01.004',  LEFT( 'RECEBIMENTOS EM CHEQUE' , 35 ),  68, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.01.005',  LEFT( 'RECEBIMENTO EM BOLETO' , 35 ),  69, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.02',  LEFT( 'RECEBIMENTOS DE EMPRESTIMOS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.02.001',  LEFT( 'RECEBIMENTO DESCONTO BOLETA B BRASIL' , 35 ),  70, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.02.002',  LEFT( 'RECEBIMENTO EMPRESTIMO BANCO DO BRASIL' , 35 ),  71, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '3.02.02.003',  LEFT( 'RECEBIMENTO EMPRESTIMO CAIXA ECONOMICA FEDERAL' , 35 ),  72, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5',  LEFT( 'RESULTADO (CONTAS TRANSITORIAS)' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.01',  LEFT( 'LUCRO' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.01.01',  LEFT( 'LUCRO' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.01.01.001',  LEFT( 'LUCRO' , 35 ),  73, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.02',  LEFT( 'TRANSFERENCIAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.02.01',  LEFT( 'TRANSFERENCIAS' , 35 ), NULL, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.02.01.001',  LEFT( 'TRANSFERENCIA DE CAIXA' , 35 ),  74, 1 )
insert into TBL_Plano_de_Contas ( NumConta, DescConta, CodConta, CodEmpresa ) values (  '5.02.01.002',  LEFT( 'TRANSFERENCIA BANCARIA' , 35 ),  75, 1 )
GO